# Source shared helpers from mfxtsemipar_cv.R.
# The path is resolved relative to this file when sourced; otherwise assumes
# the working directory is the project root.
.this_file <- tryCatch(sys.frame(1)$ofile, error = function(e) NULL)
.src_dir <- if (!is.null(.this_file)) dirname(.this_file) else "R"
source(file.path(.src_dir, "mfxtsemipar_cv.R"))


#' Mixed-frequency cross-validated binned semiparametric regression
#'
#' R implementation of Stata's \code{mfxtbin_cv}. Fits a semiparametric
#' regression where the nonparametric component is approximated by a binned
#' step function evaluated at high frequency and then aggregated to a low
#' frequency before estimation. Cross-validation is used to select the number
#' of bins.
#'
#' @param hf data.frame or data.table containing the high-frequency observations.
#'   Must include \code{id}, \code{tl} and \code{uvar}.
#' @param lf data.frame or data.table containing one observation per \code{id*tl}
#'   combination. Must include \code{id}, \code{tl} and \code{y}.
#' @param y name of the dependent variable (in \code{lf}).
#' @param x character vector of low-frequency covariates (in \code{lf}).
#' @param uvar name of the variable used for binning (in \code{hf}).
#' @param id name of the panel identifier.
#' @param tl character vector of time-level variables that define the
#'   low-frequency units (together with \code{id}).
#' @param gen name of the generated fitted-values variable.
#' @param hfcov character vector of high-frequency covariates (in \code{hf}).
#'   They are aggregated to the low-frequency level by taking means.
#' @param cluster name of the cluster variable for robust standard errors.
#' @param maxnbin maximum number of bins considered; default 5.
#' @param minnbin minimum number of bins considered; default 2.
#' @param eqspace logical; if \code{TRUE}, bins are based on equally spaced
#'   cutpoints instead of quantiles.
#' @param dropbin either an integer giving the bin number to drop, or a numeric
#'   value whose containing bin should be dropped.
#' @param startp numeric; lower bound used to form cutpoints.
#' @param endp numeric; upper bound used to form cutpoints.
#' @param cvgroup name of a variable that defines CV folds. If \code{NULL},
#'   folds are generated by clustering on \code{id}.
#' @param nfold number of CV folds when \code{cvgroup} is \code{NULL}.
#' @param seed integer random seed for fold generation.
#' @param atu name of an alternative evaluation variable in \code{hf}. If
#'   supplied, the fitted binned component is evaluated at \code{atu}
#'   instead of \code{uvar}.
#' @param absorb fixed-effects specification passed to \code{fixest::feols}.
#' @param sopt logical; if \code{TRUE}, select the first local minimum of the CV
#'   curve instead of the global minimum.
#' @param predy name of a variable for the full predicted value (xb + fixed
#'   effects) at the low-frequency level. If \code{NULL}, none is computed.
#' @param partialout \code{NULL}, \code{"all"}, or a character vector of
#'   variables to partial out.
#' @param weights name of a weight variable (in \code{hf} or \code{lf}).
#'
#' @return A list of class \code{mfxtbin_cv}.
#'
#' @details
#' The high-frequency data \code{hf} and the low-frequency data \code{lf} are
#' linked by the keys \code{id} and \code{tl}. The bin indicators are generated
#' on \code{hf}, summed within each \code{id*tl} cell, and merged into
#' \code{lf} for estimation.
#'
#' @export
mfxtbin_cv <- function(hf,
                       lf,
                       y,
                       x = NULL,
                       uvar,
                       id,
                       tl,
                       gen,
                       hfcov = NULL,
                       cluster = NULL,
                       maxnbin = 5,
                       minnbin = 2,
                       eqspace = FALSE,
                       dropbin = NULL,
                       startp = NULL,
                       endp = NULL,
                       cvgroup = NULL,
                       nfold = 10L,
                       seed = NULL,
                       atu = NULL,
                       absorb = NULL,
                       sopt = FALSE,
                       predy = NULL,
                       partialout = NULL,
                       weights = NULL) {

  # ------------------------------------------------------------------
  # 0. package checks
  # ------------------------------------------------------------------
  if (!requireNamespace("data.table", quietly = TRUE)) {
    stop("Package 'data.table' is required.")
  }
  if (!requireNamespace("fixest", quietly = TRUE)) {
    stop("Package 'fixest' is required.")
  }

  # ------------------------------------------------------------------
  # 1. basic input validation and conversion
  # ------------------------------------------------------------------
  hf <- data.table::as.data.table(hf)
  lf <- data.table::as.data.table(lf)

  if (length(tl) == 1L && is.null(names(tl))) tl <- as.character(tl)
  keys <- c(id, tl)

  miss_hf <- setdiff(c(keys, uvar, hfcov, atu), names(hf))
  if (length(miss_hf)) {
    stop("Variables not found in hf: ", paste(miss_hf, collapse = ", "))
  }
  miss_lf <- setdiff(c(keys, y, x, cluster, cvgroup), names(lf))
  if (length(miss_lf)) {
    stop("Variables not found in lf: ", paste(miss_lf, collapse = ", "))
  }

  if (!is.null(weights)) {
    if (!(weights %in% names(hf)) && !(weights %in% names(lf))) {
      stop("Weights variable not found in hf or lf: ", weights)
    }
  }

  if (anyDuplicated(lf, by = keys)) {
    stop("lf must contain exactly one row per id*tl combination.")
  }

  if (!is.numeric(hf[[uvar]])) {
    stop("uvar must be numeric.")
  }

  weights_fml <- if (!is.null(weights)) stats::as.formula(paste0("~ ", weights)) else NULL

  # ------------------------------------------------------------------
  # 2. generate CV groups
  # ------------------------------------------------------------------
  if (!is.null(cvgroup)) {
    lf[, .cv := as.integer(as.factor(get(cvgroup)))]
  } else {
    if (!is.null(seed)) set.seed(seed)
    ids <- unique(lf[[id]])
    folds <- sample(rep_len(seq_len(nfold), length(ids)))
    map <- data.table::data.table(.id = ids, .cv = folds)
    data.table::setnames(map, ".id", id)
    lf <- merge(lf, map, by = id, all.x = TRUE)
  }

  # ------------------------------------------------------------------
  # 3. split controls into main / partialout
  # ------------------------------------------------------------------
  all_controls <- unique(c(x, hfcov))
  if (is.null(partialout)) {
    x_main <- all_controls
    x_partial <- NULL
  } else if (identical(partialout, "all")) {
    x_main <- NULL
    x_partial <- all_controls
  } else {
    partialout <- as.character(partialout)
    x_partial <- intersect(partialout, all_controls)
    if (length(setdiff(partialout, all_controls))) {
      warning("Some partialout variables are not in x or hfcov: ",
              paste(setdiff(partialout, all_controls), collapse = ", "))
    }
    x_main <- setdiff(all_controls, x_partial)
  }

  # ------------------------------------------------------------------
  # 4. cross-validation over number of bins
  # ------------------------------------------------------------------
  mse_vec <- rep(NA_real_, maxnbin - minnbin + 1L)
  names(mse_vec) <- paste0("nbin=", seq(minnbin, maxnbin))

  # store cutpoints for each nbin to avoid recomputation in final step
  cutpoints_list <- vector("list", length(mse_vec))

  for (i in seq_along(mse_vec)) {
    nbin <- minnbin + i - 1L

    gb <- genbins(
      x = hf[[uvar]],
      nbin = nbin,
      eqspace = eqspace,
      startp = startp,
      endp = endp,
      prefix = ".bin_"
    )
    bin_vars <- gb$names
    cutpoints_list[[i]] <- gb$cutpoints

    # handle dropbin
    dropped <- drop_bin(bin_vars, dropbin, gb$cutpoints, hf[[uvar]])
    bin_vars <- dropped$bin_vars
    drop_name <- dropped$drop_name

    add_splines_to_hf(hf, gb$matrix, gb$names)
    if (!is.null(drop_name)) hf[, (drop_name) := NULL]

    lf_agg <- agg_hf_to_lf(
      hf = hf,
      id = id,
      tl = tl,
      spline_vars = bin_vars,
      hfcov = hfcov,
      weights = weights
    )

    hf[, (gb$names) := NULL]

    lf_cv <- merge(lf, lf_agg, by = keys, all.x = TRUE)

    mse_vec[i] <- rmse_cv(
      data = lf_cv,
      y = y,
      varlist = c(bin_vars, x_main),
      partialout = x_partial,
      absorb = absorb,
      cluster = cluster,
      weights_fml = weights_fml,
      cvvar = ".cv"
    )
  }

  # select optimal bins
  minpos <- which.min(mse_vec)
  soptbin <- minnbin + minpos - 1L

  if (sopt) {
    soptbin <- minnbin
    for (k in seq(minnbin, maxnbin)) {
      idx <- k - minnbin + 1L
      if (!is.na(mse_vec[idx]) &&
          (idx == 1L || mse_vec[idx] < mse_vec[idx - 1L])) {
        soptbin <- k
      } else {
        break
      }
    }
  }

  nstar <- if (sopt) soptbin else (minnbin + minpos - 1L)
  minmse <- mse_vec[minpos]

  cat("\nCross-validation MSE\n")
  print(data.table::data.table(nbin = seq(minnbin, maxnbin), MSE = mse_vec))
  cat("\n")

  # ------------------------------------------------------------------
  # 5. final estimation with optimal number of bins
  # ------------------------------------------------------------------
  idx_final <- nstar - minnbin + 1L
  cutpoints <- cutpoints_list[[idx_final]]

  gb <- genbins(
    x = hf[[uvar]],
    cut = cutpoints,
    prefix = ".bin_"
  )
  bin_vars <- gb$names

  dropped <- drop_bin(bin_vars, dropbin, cutpoints, hf[[uvar]])
  bin_vars <- dropped$bin_vars
  drop_name <- dropped$drop_name

  add_splines_to_hf(hf, gb$matrix, gb$names)
  if (!is.null(drop_name)) hf[, (drop_name) := NULL]

  lf_agg <- agg_hf_to_lf(
    hf = hf,
    id = id,
    tl = tl,
    spline_vars = bin_vars,
    hfcov = hfcov,
    weights = weights
  )

  hf[, (gb$names) := NULL]

  lf_est <- merge(lf, lf_agg, by = keys, all.x = TRUE)

  fml <- build_formula(y = y, varlist = c(bin_vars, x_main),
                       partialout = x_partial, absorb = absorb)
  cluster_fml <- if (!is.null(cluster)) stats::as.formula(paste0("~ ", cluster)) else NULL

  est <- fixest::feols(fml, data = lf_est, cluster = cluster_fml,
                       weights = weights_fml, warn = FALSE, notes = FALSE)

  b <- stats::coef(est)
  V <- stats::vcov(est)
  info <- fixest::fitstat(est, type = c("ll", "aic", "bic", "n"))

  # ------------------------------------------------------------------
  # 6. prediction: binned semiparametric component
  # ------------------------------------------------------------------
  eval_var <- if (!is.null(atu)) atu else uvar
  eval_x <- hf[[eval_var]]

  # atu range checks
  if (!is.null(atu)) {
    atu_min <- min(eval_x, na.rm = TRUE)
    atu_max <- max(eval_x, na.rm = TRUE)
    cp_min <- min(cutpoints)
    cp_max <- max(cutpoints)
    if (atu_min >= cp_min) {
      stop("minimum value of atu should be less than the minimum cutpoint")
    }
    if (atu_max <= cp_max) {
      stop("maximum value of atu should be greater than the maximum cutpoint")
    }
  }

  gb_eval <- genbins(
    x = eval_x,
    cut = cutpoints,
    prefix = ".bin_"
  )
  B_eval <- gb_eval$matrix
  all_bin_vars <- gb_eval$names

  # drop the same bin as in estimation
  if (!is.null(drop_name)) {
    keep_cols <- setdiff(all_bin_vars, drop_name)
    B_eval <- B_eval[, keep_cols, drop = FALSE]
    all_bin_vars <- keep_cols
  }

  retained_bin <- intersect(names(b), all_bin_vars)
  if (length(retained_bin) == 0L) {
    stop("All bin coefficients were dropped; check collinearity.")
  }
  b_bin <- b[retained_bin]

  B_eval_retained <- B_eval[, retained_bin, drop = FALSE]
  fitted_vals <- as.numeric(B_eval_retained %*% b_bin)

  V_bin <- V[retained_bin, retained_bin, drop = FALSE]
  se_vals <- sqrt(pmax(0, rowSums((B_eval_retained %*% V_bin) * B_eval_retained)))

  out_dt <- data.table::copy(hf[, c(keys, if (!is.null(atu)) atu else uvar), with = FALSE])
  out_dt[, (gen) := fitted_vals]
  out_dt[, (paste0(gen, "_se")) := se_vals]

  # ------------------------------------------------------------------
  # 7. predy: full prediction at low frequency
  # ------------------------------------------------------------------
  predy_dt <- NULL
  if (!is.null(predy)) {
    lf_est[, (predy) := stats::predict(est, type = "response")]
    predy_dt <- lf_est[, c(keys, predy), with = FALSE]
    out_dt <- merge(out_dt, predy_dt, by = keys, all.x = TRUE)
  }

  # ------------------------------------------------------------------
  # 8. return
  # ------------------------------------------------------------------
  result <- list(
    soptbin = soptbin,
    nbin = nstar,
    cutpoints = cutpoints,
    minmse = minmse,
    mse = data.table::data.table(nbin = seq(minnbin, maxnbin), MSE = mse_vec),
    type = "bin",
    uvar = uvar,
    id = id,
    tl = tl,
    coef = b,
    vcov = V,
    info = info,
    fitted = out_dt,
    predy = predy_dt,
    estimation = est,
    call = match.call()
  )

  class(result) <- c("mfxtbin_cv", "list")
  return(result)
}


# ==============================================================================
# Helper: generate bin indicators
# ==============================================================================
genbins <- function(x, nbin = NULL, cut = NULL, bw = NULL, eqspace = FALSE,
                    startp = NULL, endp = NULL, prefix = ".bin_") {
  n_spec <- sum(!sapply(list(cut, nbin, bw), is.null))
  if (n_spec == 0L) {
    stop("One of cut, nbin or bw must be supplied.")
  }
  if (n_spec > 1L) {
    stop("Only one of cut, nbin and bw can be specified at the same time.")
  }

  x_use <- x[!is.na(x)]

  if (!is.null(cut)) {
    cutpoints <- sort(unique(as.numeric(cut)))
  } else if (!is.null(bw)) {
    bw <- as.numeric(bw)
    if (length(bw) != 1L || bw <= 0) stop("bw must be a single positive number.")
    lo <- if (!is.null(startp)) startp else min(x_use)
    hi <- if (!is.null(endp)) endp else max(x_use)
    if (lo + bw > hi) {
      stop("bw is too large relative to the range of x.")
    }
    cutpoints <- seq(lo + bw, hi, by = bw)
    cutpoints <- sort(unique(cutpoints))
  } else {
    nbin <- as.integer(nbin)
    lo <- if (!is.null(startp)) startp else min(x_use)
    hi <- if (!is.null(endp)) endp else max(x_use)

    if (eqspace) {
      step <- (hi - lo) / (nbin - 1L)
      if (!is.null(endp)) {
        cutpoints <- seq(lo + step, hi, by = step)
      } else {
        # match Stata: stop slightly before max
        cutpoints <- seq(lo + step, hi - 0.98 * step, by = step)
      }
    } else {
      keep <- x_use >= lo & x_use <= hi
      if (sum(keep) < nbin) {
        stop("Not enough observations inside [startp, endp] to form bins.")
      }
      probs <- seq_len(nbin - 1L) / nbin
      cutpoints <- as.numeric(stats::quantile(x_use[keep], probs = probs, type = 2, names = FALSE))
    }

    cutpoints <- sort(unique(cutpoints))
  }

  # add startp / endp to cutpoints if provided (Stata behavior)
  if (!is.null(startp)) cutpoints <- sort(unique(c(startp, cutpoints)))
  if (!is.null(endp)) cutpoints <- sort(unique(c(cutpoints, endp)))

  nbin_out <- length(cutpoints) + 1L

  mat <- matrix(0L, nrow = length(x), ncol = nbin_out)
  for (i in seq_len(nbin_out)) {
    if (i == 1L) {
      mat[, i] <- as.integer(x < cutpoints[1L] & !is.na(x))
    } else if (i < nbin_out) {
      mat[, i] <- as.integer(x >= cutpoints[i - 1L] & x < cutpoints[i] & !is.na(x))
    } else {
      mat[, i] <- as.integer(x >= cutpoints[i - 1L] & !is.na(x))
    }
  }

  vars <- paste0(prefix, seq_len(nbin_out))
  colnames(mat) <- vars

  list(matrix = mat, names = vars, cutpoints = cutpoints, nbin = nbin_out)
}


# ==============================================================================
# Helper: determine which bin to drop
# ==============================================================================
drop_bin <- function(bin_vars, dropbin, cutpoints, x) {
  drop_name <- NULL
  if (is.null(dropbin)) {
    return(list(bin_vars = bin_vars, drop_name = drop_name))
  }

  dropbin_char <- as.character(dropbin)

  # Parse Stata-style "base(val)" syntax: extract numeric value inside base()
  if (grepl("^base\\((.+)\\)$", dropbin_char)) {
    dropbin_char <- sub("^base\\((.+)\\)$", "\\1", dropbin_char)
  }

  int_val <- suppressWarnings(as.integer(dropbin_char))

  if (!is.na(int_val) && int_val > 0L && int_val <= length(bin_vars)) {
    drop_name <- bin_vars[int_val]
  } else {
    val <- as.numeric(dropbin_char)
    if (is.na(val)) stop("dropbin must be an integer bin number or a numeric value.")
    # find bin containing val
    nbin <- length(bin_vars)
    bin_idx <- NA_integer_
    if (val < cutpoints[1L]) {
      bin_idx <- 1L
    } else if (val >= cutpoints[length(cutpoints)]) {
      bin_idx <- nbin
    } else {
      for (i in 2L:(nbin - 1L)) {
        if (val >= cutpoints[i - 1L] && val < cutpoints[i]) {
          bin_idx <- i
          break
        }
      }
    }
    if (is.na(bin_idx)) stop("Could not determine bin for dropbin value.")
    drop_name <- bin_vars[bin_idx]
  }

  list(bin_vars = setdiff(bin_vars, drop_name), drop_name = drop_name)
}


# ==============================================================================
# Predict method for binned g(u)
# ==============================================================================
#' @export
predict.mfxtbin_cv <- function(object, newdata, uvar = NULL, ...) {
  if (!inherits(object, "mfxtbin_cv")) {
    stop("object must be of class 'mfxtbin_cv'.")
  }

  if (is.numeric(newdata)) {
    x <- newdata
  } else {
    newdata <- data.table::as.data.table(newdata)
    if (is.null(uvar)) uvar <- object$uvar
    if (!(uvar %in% names(newdata))) {
      stop("Variable '", uvar, "' not found in newdata.")
    }
    x <- newdata[[uvar]]
  }

  if (!is.numeric(x)) {
    stop("Evaluation variable must be numeric.")
  }

  gb <- genbins(
    x = x,
    cut = object$cutpoints,
    prefix = ".bin_"
  )
  B <- gb$matrix
  bin_vars <- gb$names

  retained <- intersect(names(object$coef), bin_vars)
  if (length(retained) == 0L) {
    stop("No bin coefficients available for prediction.")
  }

  b <- object$coef[retained]
  B_retained <- B[, retained, drop = FALSE]

  fit <- as.numeric(B_retained %*% b)

  V <- object$vcov[retained, retained, drop = FALSE]
  se <- sqrt(pmax(0, rowSums((B_retained %*% V) * B_retained)))

  data.table::data.table(u = x, g = fit, se = se)
}


# ==============================================================================
# Diagnostic method for mfxtbin_cv
# ==============================================================================
#' @export
g_diagnostic.mfxtbin_cv <- function(object, newdata, true_g, uvar = NULL) {
  pred <- predict.mfxtbin_cv(object, newdata = newdata, uvar = uvar)
  compute_g_diagnostic(pred, true_g)
}


# ==============================================================================
# Print method
# ==============================================================================
#' @export
print.mfxtbin_cv <- function(x, ...) {
  cat("Mixed-frequency binned semiparametric regression with cross-validation\n")
  cat("  Selected bins: ", x$nbin, "\n", sep = "")
  cat("  Cutpoints: ", paste(round(x$cutpoints, 4), collapse = ", "), "\n", sep = "")
  cat("  Minimum CV MSE: ", round(x$minmse, 6), "\n", sep = "")
  cat("  Simple optimal bins: ", x$soptbin, "\n", sep = "")
  cat("\nCV MSE by number of bins:\n")
  print(x$mse, row.names = FALSE)
  invisible(x)
}
