#' Mixed-frequency cross-validated semiparametric regression
#'
#' R fits a semiparametric
#' regression where the nonparametric component is evaluated at high frequency
#' and then aggregated to a low frequency before estimation. Cross-validation is
#' used to select the number of knots.
#'
#' @param hf data.frame or data.table containing the high-frequency observations.
#'   Must include \code{id}, \code{tl} and \code{uvar}.
#' @param lf data.frame or data.table containing one observation per \code{id*tl}
#'   combination. Must include \code{id}, \code{tl} and \code{y}.
#' @param y name of the dependent variable (in \code{lf}).
#' @param x character vector of low-frequency covariates (in \code{lf}).
#' @param uvar name of the variable used for the semiparametric transformation
#'   (in \code{hf}).
#' @param id name of the panel identifier.
#' @param tl character vector of time-level variables that define the
#'   low-frequency units (together with \code{id}).
#' @param gen name of the generated fitted-values variable.
#' @param hfcov character vector of high-frequency covariates (in \code{hf}).
#'   They are aggregated to the low-frequency level by taking means.
#' @param cluster name of the cluster variable for robust standard errors.
#' @param type spline type: \code{"poly"}, \code{"bs"}, \code{"ms"},
#'   \code{"is"} or \code{"ibs"}. Default is \code{"poly"}.
#' @param winsor numeric vector of length 2, low and high percentiles for
#'   winsorizing \code{uvar}. Use \code{winsor_values = TRUE} to supply raw
#'   values instead of percentiles.
#' @param winsor_values logical; see \code{winsor}.
#' @param eqspace logical; if \code{TRUE}, knots are placed at equally spaced
#'   intervals instead of quantiles.
#' @param bknots numeric vector of length 2 with boundary knots for the spline
#'   basis. If \code{NULL} (default), boundary knots are set to the minimum and
#'   maximum of \code{uvar} (with a small padding). When supplied, the minimum
#'   and maximum of \code{uvar} must lie within \code{bknots}; otherwise an
#'   error is raised. Interior knot locations are still determined from
#'   \code{uvar}'s range or from \code{startp}/\code{endp}, not from
#'   \code{bknots}.
#' @param startp numeric; optional preset minimum internal knot. Together with
#'   \code{endp}, interior knots are placed between \code{startp} and
#'   \code{endp}; otherwise they follow the range of \code{uvar}.
#' @param endp numeric; optional preset maximum internal knot.
#' @param maxnk integer; maximum number of knots considered.
#' @param minnk integer; minimum number of knots considered.
#' @param center numeric; centering value for the spline basis.
#' @param absorb fixed-effects specification passed to \code{fixest::feols}.
#'   Can be a one-sided formula (e.g. \code{~ id + year}) or a character vector
#'   (e.g. \code{c("id", "year")}).
#' @param partialout \code{NULL} (no partial out), \code{"all"} (partial out
#'   all covariates, equivalent to Stata's \code{partialout}), or a character
#'   vector of variable names (equivalent to Stata's \code{partialout1(...)}).
#' @param cvgroup name of a variable that defines CV folds. If \code{NULL},
#'   folds are generated by clustering on \code{id}.
#' @param nfold number of CV folds when \code{cvgroup} is \code{NULL}.
#' @param seed integer random seed for fold generation.
#' @param degree polynomial degree for polynomial splines.
#' @param keepsplines logical; if \code{TRUE}, the generated spline columns are
#'   kept in the returned fitted object.
#' @param atu name of an alternative evaluation variable in \code{hf}. If
#'   supplied, the fitted semiparametric component is evaluated at \code{atu}
#'   instead of \code{uvar}.
#' @param dropfirstbase logical; if \code{TRUE}, the intercept/base term is
#'   dropped from the spline basis.
#' @param sopt logical; if \code{TRUE}, select the first local minimum of the CV
#'   curve instead of the global minimum.
#' @param brep number of wild-bootstrap replications for inference. Default 0.
#' @param predy name of a variable for the full predicted value (xb + fixed
#'   effects) at the low-frequency level. If \code{NULL}, none is computed.
#' @param weights name of a weight variable. Currently frequency, analytic and
#'   sampling weights are supported through \code{fixest}.
#'
#' @return A list with components \code{nknots}, \code{knots}, \code{cv_mse},
#'   \code{min_cv_mse}, \code{rmse}, \code{soptnk}, \code{coef}, \code{vcov},
#'   \code{info}, \code{fitted} (a data.table with \code{id}, \code{tl},
#'   \code{gen} and \code{gen_se}), and the full \code{fixest} estimation object.
#'   \code{cv_mse} is a data.table of cross-validated RMSE by knot count (used to
#'   select \code{nknots}); \code{min_cv_mse} is the minimum of that curve;
#'   \code{rmse} is the in-sample RMSE of the final \code{fixest::feols} fit.
#'
#' @details
#' The high-frequency data \code{hf} and the low-frequency data \code{lf} are
#' linked by the keys \code{id} and \code{tl}. The spline basis is generated on
#' \code{hf}, summed within each \code{id*tl} cell, and merged into \code{lf}
#' for estimation. This avoids storing the expanded spline basis at low
#' frequency and keeps memory use low.
#'
#' @export
mfxtsemipar_cv <- function(hf,
                           lf,
                           y,
                           x = NULL,
                           uvar,
                           id,
                           tl,
                           gen,
                           hfcov = NULL,
                           cluster = NULL,
                           type = "poly",
                           winsor = NULL,
                           winsor_values = FALSE,
                           eqspace = FALSE,
                           bknots = NULL,
                           startp = NULL,
                           endp = NULL,
                           maxnk = 5L,
                           minnk = 2L,
                           center = NULL,
                           absorb = NULL,
                           partialout = NULL,
                           cvgroup = NULL,
                           nfold = 10L,
                           seed = NULL,
                           degree = 1L,
                           keepsplines = FALSE,
                           atu = NULL,
                           dropfirstbase = FALSE,
                           sopt = FALSE,
                           brep = 0L,
                           predy = NULL,
                           weights = NULL) {

  # ------------------------------------------------------------------
  # 0. package checks
  # ------------------------------------------------------------------
  if (!requireNamespace("data.table", quietly = TRUE)) {
    stop("Package 'data.table' is required.")
  }
  if (!requireNamespace("fixest", quietly = TRUE)) {
    stop("Package 'fixest' is required.")
  }
  if (!type %in% c("poly", "bs", "ms", "is", "ibs")) {
    stop("type must be one of 'poly', 'bs', 'ms', 'is', 'ibs'.")
  }
  if (type %in% c("ms", "is", "ibs") &&
      !requireNamespace("splines2", quietly = TRUE)) {
    stop("Package 'splines2' is required for type 'ms', 'is' and 'ibs'.")
  }

  # ------------------------------------------------------------------
  # 1. basic input validation and conversion
  # ------------------------------------------------------------------
  hf <- data.table::as.data.table(hf)
  lf <- data.table::as.data.table(lf)

  if (length(tl) == 1L && is.null(names(tl))) tl <- as.character(tl)
  keys <- c(id, tl)

  miss_hf <- setdiff(c(keys, uvar, hfcov, atu), names(hf))
  if (length(miss_hf)) {
    stop("Variables not found in hf: ", paste(miss_hf, collapse = ", "))
  }
  miss_lf <- setdiff(c(keys, y, x, cluster, cvgroup), names(lf))
  if (length(miss_lf)) {
    stop("Variables not found in lf: ", paste(miss_lf, collapse = ", "))
  }

  if (!is.null(weights)) {
    if (!(weights %in% names(hf)) && !(weights %in% names(lf))) {
      stop("Weights variable not found in hf or lf: ", weights)
    }
  }

  if (anyDuplicated(lf, by = keys)) {
    stop("lf must contain exactly one row per id*tl combination.")
  }

  if (!is.numeric(hf[[uvar]])) {
    stop("uvar must be numeric.")
  }

  weights_fml <- if (!is.null(weights)) stats::as.formula(paste0("~ ", weights)) else NULL

  # ------------------------------------------------------------------
  # 2. winsorize uvar if requested
  # ------------------------------------------------------------------
  if (!is.null(winsor)) {
    if (length(winsor) != 2L) {
      stop("winsor must be a numeric vector of length 2.")
    }
    if (winsor_values) {
      wlow <- winsor[1L]
      whigh <- winsor[2L]
    } else {
      quants <- stats::quantile(hf[[uvar]], probs = winsor / 100,
                                na.rm = TRUE, names = FALSE)
      wlow <- quants[1L]
      whigh <- quants[2L]
    }
    hf[, (uvar) := pmin(pmax(get(uvar), wlow), whigh)]
  }

  # ------------------------------------------------------------------
  # 3. determine knot boundaries
  # ------------------------------------------------------------------
  uvals <- hf[[uvar]]
  umin_data <- min(uvals, na.rm = TRUE)
  umax_data <- max(uvals, na.rm = TRUE)
  if (!is.finite(umin_data) || !is.finite(umax_data)) {
    stop("No non-missing observations available in uvar.")
  }

  if (is.null(bknots)) {
    bknots <- c(umin_data - 0.01, umax_data + 0.01)
  } else {
    bknots <- as.numeric(bknots)
    if (length(bknots) != 2L) {
      stop("bknots must be a numeric vector of length 2.")
    }
    if (bknots[1L] >= bknots[2L]) {
      stop("bknots must be strictly ascending.")
    }
    if (umin_data < bknots[1L]) {
      stop("Minimum uvar value (", umin_data,
           ") is below the lower boundary knot (", bknots[1L], ").",
           call. = FALSE)
    }
    if (umax_data > bknots[2L]) {
      stop("Maximum uvar value (", umax_data,
           ") is above the upper boundary knot (", bknots[2L], ").",
           call. = FALSE)
    }
  }

  if (!is.null(startp) && !is.numeric(startp)) {
    stop("startp must be numeric.")
  }
  if (!is.null(endp) && !is.numeric(endp)) {
    stop("endp must be numeric.")
  }
  if (!is.null(startp) && !is.null(endp) && startp >= endp) {
    stop("startp must be strictly less than endp.")
  }
  n_fixed_knots <- (!is.null(startp)) + (!is.null(endp))
  if (minnk < n_fixed_knots) {
    stop("minnk must be at least the number of specified startp/endp knots (",
         n_fixed_knots, ").", call. = FALSE)
  }

  # ------------------------------------------------------------------
  # 4. generate CV groups
  # ------------------------------------------------------------------
  if (!is.null(cvgroup)) {
    lf[, .cv := as.integer(as.factor(get(cvgroup)))]
  } else {
    if (!is.null(seed)) set.seed(seed)
    ids <- unique(lf[[id]])
    folds <- sample(rep_len(seq_len(nfold), length(ids)))
    map <- data.table::data.table(.id = ids, .cv = folds)
    data.table::setnames(map, ".id", id)
    lf <- merge(lf, map, by = id, all.x = TRUE)
  }

  # ------------------------------------------------------------------
  # 5. split controls into main / partialout
  # ------------------------------------------------------------------
  all_controls <- unique(c(x, hfcov))
  if (is.null(partialout)) {
    x_main <- all_controls
    x_partial <- NULL
  } else if (identical(partialout, "all")) {
    x_main <- NULL
    x_partial <- all_controls
  } else {
    partialout <- as.character(partialout)
    x_partial <- intersect(partialout, all_controls)
    if (length(setdiff(partialout, all_controls))) {
      warning("Some partialout variables are not in x or hfcov: ",
              paste(setdiff(partialout, all_controls), collapse = ", "))
    }
    x_main <- setdiff(all_controls, x_partial)
  }

  # ------------------------------------------------------------------
  # 6. cross-validation over nknots
  # ------------------------------------------------------------------
  cv_rmse_vec <- rep(NA_real_, maxnk - minnk + 1L)
  names(cv_rmse_vec) <- paste0("nk=", seq(minnk, maxnk))

  for (i in seq_along(cv_rmse_vec)) {
    nk <- minnk + i - 1L

    knots <- gennknots(hf[[uvar]], nknots = nk, eqspace = eqspace,
                       startp = startp, endp = endp)

    sp <- make_splines(
      x = hf[[uvar]],
      type = type,
      knots = knots,
      bknots = bknots,
      degree = degree,
      center = center,
      intercept = !dropfirstbase,
      prefix = ".Spline_"
    )
    spline_vars <- sp$names
    add_splines_to_hf(hf, sp$matrix, spline_vars)

    lf_agg <- agg_hf_to_lf(
      hf = hf,
      id = id,
      tl = tl,
      spline_vars = spline_vars,
      hfcov = hfcov,
      weights = weights
    )

    # remove temporary spline columns from hf to save memory
    hf[, (spline_vars) := NULL]

    lf_cv <- merge(lf, lf_agg, by = keys, all.x = TRUE)

    cv_rmse_vec[i] <- rmse_cv(
      data = lf_cv,
      y = y,
      varlist = c(spline_vars, x_main),
      partialout = x_partial,
      absorb = absorb,
      cluster = cluster,
      weights_fml = weights_fml,
      cvvar = ".cv"
    )
  }

  # select optimal knots
  minpos <- which.min(cv_rmse_vec)
  soptnk <- minnk + minpos - 1L

  if (sopt) {
    soptnk <- minnk
    for (k in seq(minnk, maxnk)) {
      idx <- k - minnk + 1L
      if (!is.na(cv_rmse_vec[idx]) &&
          (idx == 1L || cv_rmse_vec[idx] < cv_rmse_vec[idx - 1L])) {
        soptnk <- k
      } else {
        break
      }
    }
  }

  nknots <- if (sopt) soptnk else (minnk + minpos - 1L)
  min_cv_mse <- cv_rmse_vec[minpos]

  cat("\nCross-validation RMSE (for knot selection)\n")
  print(data.table::data.table(nk = seq(minnk, maxnk), cv_rmse = cv_rmse_vec))
  cat("\n")

  # ------------------------------------------------------------------
  # 7. final estimation with optimal knots
  # ------------------------------------------------------------------
  knots <- gennknots(hf[[uvar]], nknots = nknots, eqspace = eqspace,
                     startp = startp, endp = endp)

  sp <- make_splines(
    x = hf[[uvar]],
    type = type,
    knots = knots,
    bknots = bknots,
    degree = degree,
    center = center,
    intercept = !dropfirstbase,
    prefix = ".Spline_"
  )
  spline_vars <- sp$names
  spline_cmd <- sp$call
  add_splines_to_hf(hf, sp$matrix, spline_vars)

  lf_agg <- agg_hf_to_lf(
    hf = hf,
    id = id,
    tl = tl,
    spline_vars = spline_vars,
    hfcov = hfcov,
    weights = weights
  )

  hf[, (spline_vars) := NULL]

  lf_est <- merge(lf, lf_agg, by = keys, all.x = TRUE)

  fml <- build_formula(y = y, varlist = c(spline_vars, x_main),
                       partialout = x_partial, absorb = absorb)
  cluster_fml <- if (!is.null(cluster)) stats::as.formula(paste0("~ ", cluster)) else NULL

  est <- fixest::feols(fml, data = lf_est, cluster = cluster_fml,
                       weights = weights_fml, warn = FALSE, notes = FALSE)

  # ------------------------------------------------------------------
  # 8. bootstrap inference if requested
  # ------------------------------------------------------------------
  if (brep > 0L) {
    V <- wildboot_vcov(
      data = lf_est,
      y = y,
      varlist = c(spline_vars, x_main),
      partialout = x_partial,
      absorb = absorb,
      cluster = cluster,
      weights_fml = weights_fml,
      brep = brep,
      seed = seed
    )
    b <- stats::coef(est)
    est$vcov <- V
    est$cov.scaled <- V
  } else {
    b <- stats::coef(est)
    V <- stats::vcov(est)
  }

  info <- fixest::fitstat(est, type = c("ll", "aic", "bic", "n"))
  rmse <- sqrt(mean(stats::residuals(est)^2, na.rm = TRUE))

  # ------------------------------------------------------------------
  # 9. prediction: semiparametric component
  # ------------------------------------------------------------------
  eval_var <- if (!is.null(atu)) atu else uvar
  eval_x <- hf[[eval_var]]

  sp_eval <- make_splines(
    x = eval_x,
    type = type,
    knots = knots,
    bknots = bknots,
    degree = degree,
    center = center,
    intercept = !dropfirstbase,
    prefix = ".Spline_"
  )
  B_eval <- sp_eval$matrix

  retained_spline <- intersect(names(b), spline_vars)
  if (length(retained_spline) == 0L) {
    stop("All spline coefficients were dropped; check collinearity.")
  }
  b_spline <- b[retained_spline]

  B_eval_retained <- B_eval[, retained_spline, drop = FALSE]
  fitted_vals <- as.numeric(B_eval_retained %*% b_spline)

  V_spline <- V[retained_spline, retained_spline, drop = FALSE]
  se_vals <- sqrt(pmax(0, rowSums((B_eval_retained %*% V_spline) * B_eval_retained)))

  out_dt <- data.table::copy(hf[, c(keys, if (!is.null(atu)) atu else uvar), with = FALSE])
  out_dt[, (gen) := fitted_vals]
  out_dt[, (paste0(gen, "_se")) := se_vals]

  if (keepsplines) {
    for (j in seq_along(spline_vars)) {
      out_dt[, (spline_vars[j]) := B_eval[, j]]
    }
  }

  # ------------------------------------------------------------------
  # 10. predy: full prediction at low frequency
  # ------------------------------------------------------------------
  predy_dt <- NULL
  if (!is.null(predy)) {
    lf_est[, (predy) := stats::predict(est, type = "response")]
    predy_dt <- lf_est[, c(keys, predy), with = FALSE]
    out_dt <- merge(out_dt, predy_dt, by = keys, all.x = TRUE)
  }

  # ------------------------------------------------------------------
  # 11. return
  # ------------------------------------------------------------------
  result <- list(
    soptnk = soptnk,
    nknots = nknots,
    knots = knots,
    bknots = bknots,
    min_cv_mse = min_cv_mse,
    cv_mse = data.table::data.table(nk = seq(minnk, maxnk), cv_rmse = cv_rmse_vec),
    rmse = rmse,
    splinecmd = spline_cmd,
    type = type,
    degree = degree,
    center = if (is.null(center)) 0 else center,
    intercept = !dropfirstbase,
    uvar = uvar,
    startp = startp,
    endp = endp,
    id = id,
    tl = tl,
    coef = b,
    vcov = V,
    info = info,
    fitted = out_dt,
    predy = predy_dt,
    estimation = est,
    call = match.call()
  )

  class(result) <- c("mfxtsemipar_cv", "list")
  return(result)
}


# ==============================================================================
# Helper: generate knots
# ==============================================================================
gennknots <- function(x, nknots, eqspace = FALSE,
                      startp = NULL, endp = NULL) {
  x <- x[!is.na(x)]
  if (length(x) == 0L) {
    stop("No non-missing observations available to form knots.")
  }

  n_fixed <- (!is.null(startp)) + (!is.null(endp))
  n_middle <- as.integer(nknots - n_fixed)
  if (n_middle < 0L) {
    stop("nknots must be at least the number of specified startp/endp knots.")
  }

  lo <- if (!is.null(startp)) startp else min(x)
  hi <- if (!is.null(endp)) endp else max(x)
  if (!is.finite(lo) || !is.finite(hi) || lo >= hi) {
    stop("Invalid knot range: startp must be strictly less than endp.")
  }

  if (n_middle == 0L) {
    cuts <- c(
      if (!is.null(startp)) startp,
      if (!is.null(endp)) endp
    )
    return(cuts)
  }

  if (eqspace) {
    step <- (hi - lo) / (n_middle + 1L)
    middle <- seq(lo + step, hi - step, length.out = n_middle)
  } else {
    if (!is.null(startp) && !is.null(endp)) {
      keep <- x >= startp & x < endp
    } else if (!is.null(endp)) {
      keep <- x < endp
    } else if (!is.null(startp)) {
      keep <- x >= startp
    } else {
      keep <- rep(TRUE, length(x))
    }

    if (sum(keep) < n_middle + 1L) {
      stop("Not enough observations inside [startp, endp] to form knots.")
    }
    probs <- seq_len(n_middle) / (n_middle + 1L)
    middle <- as.numeric(stats::quantile(x[keep], probs = probs,
                                         type = 2, names = FALSE))
  }

  cuts <- c(
    if (!is.null(startp)) startp,
    middle,
    if (!is.null(endp)) endp
  )
  return(cuts)
}


# ==============================================================================
# Helper: build spline basis
# ==============================================================================
make_splines <- function(x, type, knots, bknots, degree = 1L,
                         center = NULL, intercept = TRUE,
                         prefix = ".Spline_") {
  if (is.null(center)) center <- 0

  out <- switch(type,
    poly = polysplines(x, knots, degree, center, intercept, prefix),
    bs   = bs_splines(x, knots, bknots, degree, center, intercept, prefix),
    ms   = ms_splines(x, knots, bknots, degree, intercept, prefix),
    is   = is_splines(x, knots, bknots, degree, intercept, prefix),
    ibs  = ibs_splines(x, knots, bknots, degree, intercept, prefix)
  )

  out$call <- paste0(
    type, " splines: degree=", degree,
    ", knots=c(", paste(round(knots, 4), collapse = ", "),
    "), bknots=c(", paste(round(bknots, 4), collapse = ", "), ")"
  )
  return(out)
}


polysplines <- function(x, knots, degree = 1L, center = 0,
                        intercept = TRUE, prefix = ".Spline_") {
  n <- length(x)
  p <- as.integer(degree)
  j <- 1L
  vars <- character()
  mat <- matrix(0, nrow = n, ncol = 0L)

  for (pow in seq_len(p)) {
    v <- paste0(prefix, j)
    vars <- c(vars, v)
    mat <- cbind(mat, x^pow - center^pow)
    j <- j + 1L
  }

  for (k in knots) {
    v <- paste0(prefix, j)
    vars <- c(vars, v)
    mat <- cbind(mat,
      (x - k)^p * (x > k) - (center - k)^p * (center > k)
    )
    j <- j + 1L
  }

  if (intercept) {
    v0 <- paste0(prefix, "0")
    vars <- c(v0, vars)
    mat <- cbind(1, mat)
  }

  colnames(mat) <- vars
  list(matrix = mat, names = vars)
}


bs_splines <- function(x, knots, bknots, degree = 3L, center = 0,
                       intercept = TRUE, prefix = ".Spline_") {
  # Use splines2::bSpline to match Stata gensplines type(bs)
  B <- splines2::bSpline(x, knots = knots, Boundary.knots = bknots,
                         degree = degree, intercept = intercept)
  B <- as.matrix(B)

  # Apply centering (centerv): B(x) - B(center)
  B_center <- splines2::bSpline(center, knots = knots, Boundary.knots = bknots,
                               degree = degree, intercept = intercept)
  B <- sweep(B, 2, as.numeric(B_center), "-")

  start_idx <- ifelse(intercept, 0L, 1L)
  vars <- paste0(prefix, start_idx:(start_idx + ncol(B) - 1L))
  colnames(B) <- vars
  list(matrix = B, names = vars)
}


ms_splines <- function(x, knots, bknots, degree = 3L,
                       intercept = TRUE, prefix = ".Spline_") {
  B <- splines2::mSpline(x, knots = knots, Boundary.knots = bknots,
                         degree = degree, intercept = intercept)
  vars <- paste0(prefix, seq_len(ncol(B)) - ifelse(intercept, 1L, 0L))
  colnames(B) <- vars
  list(matrix = as.matrix(B), names = vars)
}


is_splines <- function(x, knots, bknots, degree = 2L,
                       intercept = TRUE, prefix = ".Spline_") {
  B <- splines2::iSpline(x, knots = knots, Boundary.knots = bknots,
                         degree = degree, intercept = intercept)
  vars <- paste0(prefix, seq_len(ncol(B)) - ifelse(intercept, 1L, 0L))
  colnames(B) <- vars
  list(matrix = as.matrix(B), names = vars)
}


ibs_splines <- function(x, knots, bknots, degree = 3L,
                        intercept = TRUE, prefix = ".Spline_") {
  B <- splines2::ibs(x, knots = knots, Boundary.knots = bknots,
                     degree = degree, intercept = intercept)
  vars <- paste0(prefix, seq_len(ncol(B)) - ifelse(intercept, 1L, 0L))
  colnames(B) <- vars
  list(matrix = as.matrix(B), names = vars)
}


# ==============================================================================
# Helper: attach spline matrix to hf without copying
# ==============================================================================
add_splines_to_hf <- function(hf, mat, names) {
  for (j in seq_along(names)) {
    data.table::set(hf, j = names[j], value = mat[, j])
  }
}


# ==============================================================================
# Helper: aggregate high-frequency spline basis to low frequency
# ==============================================================================
agg_hf_to_lf <- function(hf, id, tl, spline_vars,
                         hfcov = NULL, weights = NULL) {
  keys <- c(id, tl)

  agg <- hf[, lapply(.SD, sum, na.rm = TRUE), by = keys, .SDcols = spline_vars]

  if (length(hfcov)) {
    means <- hf[, lapply(.SD, mean, na.rm = TRUE), by = keys, .SDcols = hfcov]
    agg <- merge(agg, means, by = keys, all.x = TRUE)
  }

  if (!is.null(weights) && weights %in% names(hf)) {
    wmean <- hf[, lapply(.SD, mean, na.rm = TRUE), by = keys, .SDcols = weights]
    agg <- merge(agg, wmean, by = keys, all.x = TRUE)
  }

  return(agg)
}


# ==============================================================================
# Helper: build fixest formula (no weights here)
# ==============================================================================
build_formula <- function(y, varlist, partialout = NULL, absorb = NULL) {
  rhs <- paste(c(varlist, partialout), collapse = " + ")
  if (nzchar(rhs)) {
    fml <- paste0(y, " ~ ", rhs)
  } else {
    fml <- paste0(y, " ~ 0")
  }

  if (!is.null(absorb)) {
    if (inherits(absorb, "formula")) {
      abs_txt <- paste(deparse(absorb), collapse = "")
      abs_txt <- sub("^\\s*~\\s*", "", abs_txt)
    } else {
      abs_txt <- paste(absorb, collapse = " + ")
    }
    fml <- paste0(fml, " | ", abs_txt)
  }

  stats::as.formula(fml)
}


# ==============================================================================
# Helper: residualization formula (matches reghdfe y depvar [partialout] [, absorb])
# ==============================================================================
fml_residualize <- function(y, x_partial = NULL, absorb = NULL) {
  if (length(x_partial) > 0L || !is.null(absorb)) {
    build_formula(y = y, varlist = x_partial, partialout = NULL, absorb = absorb)
  } else {
    stats::as.formula(paste0(y, " ~ 1"))
  }
}


# ==============================================================================
# Helper: save outf data to file
# ==============================================================================
outf_save <- function(dt, save, replace = FALSE) {
  if (!replace && file.exists(save)) {
    stop("File '", save, "' already exists. Use replace = TRUE to overwrite.")
  }
  ext <- tolower(tools::file_ext(save))
  if (ext == "csv") {
    data.table::fwrite(dt, save)
  } else if (ext %in% c("rdata", "rda")) {
    outf_data <- dt
    save(outf_data, file = save)
  } else {
    saveRDS(dt, save)
  }
}


# ==============================================================================
# Helper: cross-validation RMSE
# ==============================================================================
rmse_cv <- function(data, y, varlist, partialout = NULL,
                    absorb = NULL, cluster = NULL, weights_fml = NULL,
                    cvvar = ".cv") {
  data <- data.table::as.data.table(data)
  folds <- sort(unique(data[[cvvar]]))

  resi2 <- numeric(nrow(data))
  nvars <- length(varlist)

  fml <- build_formula(y = y, varlist = varlist,
                       partialout = partialout, absorb = absorb)
  cluster_fml <- if (!is.null(cluster)) stats::as.formula(paste0("~ ", cluster)) else NULL

  for (f in folds) {
    train <- data[get(cvvar) != f]
    val   <- data[get(cvvar) == f]

    fit <- fixest::feols(fml, data = train, cluster = cluster_fml,
                         weights = weights_fml, warn = FALSE, notes = FALSE)

    b <- stats::coef(fit)
    # allow for collinear drops: keep only coefficients that correspond to varlist
    retained <- intersect(names(b), varlist)
    if (length(retained) == 0L) {
      stop("All varlist variables were dropped; check collinearity.")
    }
    b <- b[retained]

    X_val <- as.matrix(val[, retained, with = FALSE])
    y_val <- val[[y]]
    gjhat <- as.numeric(X_val %*% b)
    resid <- y_val - gjhat

    val_fit <- NULL
    if (length(partialout)) {
      val_dt <- data.table::as.data.table(val)
      val_dt[, .resid := resid]
      val_fml <- build_formula(y = ".resid", varlist = partialout,
                               partialout = NULL, absorb = absorb)
      val_fit <- tryCatch(
        fixest::feols(val_fml, data = val_dt, cluster = cluster_fml,
                      weights = weights_fml, warn = FALSE, notes = FALSE),
        error = function(e) NULL
      )
    }

    if (is.null(val_fit) && !is.null(absorb)) {
      # fall back to fixed-effects only (all partialout vars collinear with FE)
      val_dt <- data.table::as.data.table(val)
      val_dt[, .resid := resid]
      val_fml <- build_formula(y = ".resid", varlist = NULL,
                               partialout = NULL, absorb = absorb)
      val_fit <- fixest::feols(val_fml, data = val_dt, cluster = cluster_fml,
                               weights = weights_fml, warn = FALSE, notes = FALSE)
    }

    if (!is.null(val_fit)) {
      yhat_val <- stats::predict(val_fit, type = "response")
      err <- resid - yhat_val
    } else {
      err <- resid
    }

    resi2[data[[cvvar]] == f] <- err^2
  }

  return(sqrt(mean(resi2, na.rm = TRUE)))
}


# ==============================================================================
# Helper: wild bootstrap vcov
# ==============================================================================
wildboot_vcov <- function(data, y, varlist, partialout = NULL,
                          absorb = NULL, cluster = NULL, weights_fml = NULL,
                          brep = 100L, seed = NULL) {
  if (!is.null(seed)) set.seed(seed)

  fml <- build_formula(y = y, varlist = varlist,
                       partialout = partialout, absorb = absorb)
  cluster_fml <- if (!is.null(cluster)) stats::as.formula(paste0("~ ", cluster)) else NULL

  fit0 <- fixest::feols(fml, data = data, cluster = cluster_fml,
                        weights = weights_fml, warn = FALSE, notes = FALSE)
  b <- stats::coef(fit0)
  k <- length(b)

  yhat <- stats::predict(fit0, type = "response")
  ehat <- data[[y]] - yhat

  bb <- matrix(NA_real_, nrow = brep, ncol = k)
  data_dt <- data.table::copy(data.table::as.data.table(data))

  for (r in seq_len(brep)) {
    if (is.null(cluster)) {
      radw <- sample(c(-1L, 1L), size = nrow(data_dt), replace = TRUE) * ehat
    } else {
      cl <- data_dt[[cluster]]
      ucl <- unique(cl)
      signs <- sample(c(-1L, 1L), size = length(ucl), replace = TRUE)
      names(signs) <- as.character(ucl)
      radw <- signs[as.character(cl)] * ehat
    }

    data_dt[, .ystar := yhat + radw]
    fml_star <- build_formula(y = ".ystar", varlist = varlist,
                              partialout = partialout, absorb = absorb)
    fit_star <- fixest::feols(fml_star, data = data_dt, cluster = cluster_fml,
                              weights = weights_fml, warn = FALSE, notes = FALSE)
    b_star <- stats::coef(fit_star)
    # align by name in case of collinear drops
    idx <- match(names(b), names(b_star))
    bb[r, !is.na(idx)] <- b_star[idx[!is.na(idx)]]
  }

  data_dt[, .ystar := NULL]

  V <- stats::cov(bb)
  rownames(V) <- colnames(V) <- names(b)
  return(V)
}


# ==============================================================================
# Print method
# ==============================================================================
#' @export
print.mfxtsemipar_cv <- function(x, ...) {
  cat("Mixed-frequency semiparametric regression with cross-validation\n")
  cat("  Selected knots: ", x$nknots, "\n", sep = "")
  cat("  Boundary knots: ", paste(round(x$bknots, 4), collapse = ", "), "\n", sep = "")
  cat("  Knot locations: ", paste(round(x$knots, 4), collapse = ", "), "\n", sep = "")
  cat("  Minimum CV RMSE: ", round(x$min_cv_mse, 6), "\n", sep = "")
  cat("  Final fit RMSE: ", round(x$rmse, 6), "\n", sep = "")
  cat("  Simple optimal knots: ", x$soptnk, "\n", sep = "")
  cat("\nCV RMSE by number of knots:\n")
  print(x$cv_mse, row.names = FALSE)
  invisible(x)
}


# ==============================================================================
# Predict method for g(u)
# ==============================================================================
#' Predict the semiparametric component g(u) from an mfxtsemipar_cv fit
#'
#' Given a new set of values for the semiparametric variable \code{uvar},
#' reconstructs the spline basis using the estimated knots and settings, then
#' returns the fitted semiparametric component and its delta-method standard
#' error.
#'
#' @param object an object of class \code{mfxtsemipar_cv}.
#' @param newdata a data.frame or data.table containing the evaluation variable,
#'   or a numeric vector of evaluation points.
#' @param uvar name of the evaluation variable in \code{newdata}. If
#'   \code{NULL}, the \code{uvar} used in estimation is used.
#' @param ... additional arguments (currently ignored).
#'
#' @return A data.table with columns \code{uvar}, \code{fit} (the predicted
#'   g(u)), and \code{se}.
#'
#' @export
predict.mfxtsemipar_cv <- function(object, newdata, uvar = NULL, ...) {
  if (!inherits(object, "mfxtsemipar_cv")) {
    stop("object must be of class 'mfxtsemipar_cv'.")
  }

  if (is.numeric(newdata)) {
    x <- newdata
    if (is.null(uvar)) uvar <- object$uvar
  } else {
    newdata <- data.table::as.data.table(newdata)
    if (is.null(uvar)) uvar <- object$uvar
    if (!(uvar %in% names(newdata))) {
      stop("Variable '", uvar, "' not found in newdata.")
    }
    x <- newdata[[uvar]]
  }

  if (!is.numeric(x)) {
    stop("Evaluation variable must be numeric.")
  }

  sp <- make_splines(
    x = x,
    type = object$type,
    knots = object$knots,
    bknots = object$bknots,
    degree = object$degree,
    center = object$center,
    intercept = object$intercept,
    prefix = ".Spline_"
  )
  B <- sp$matrix
  spline_vars <- sp$names

  retained <- intersect(names(object$coef), spline_vars)
  if (length(retained) == 0L) {
    stop("No spline coefficients available for prediction.")
  }

  b <- object$coef[retained]
  B_retained <- B[, retained, drop = FALSE]

  fit <- as.numeric(B_retained %*% b)

  V <- object$vcov[retained, retained, drop = FALSE]
  se <- sqrt(pmax(0, rowSums((B_retained %*% V) * B_retained)))

  out <- data.table::data.table(u = x, g = fit, se = se)
  out
}


# ==============================================================================
# Diagnostic: compare estimated g(u) to true g(u)
# ==============================================================================
#' Compare the estimated semiparametric component to a true g(u)
#'
#' Predicts g(u) at the evaluation points provided in \code{newdata} and reports
#' standard accuracy metrics against the supplied true values.
#'
#' @param object an object of class \code{mfxtsemipar_cv}.
#' @param newdata a data.frame or data.table containing the evaluation variable,
#'   or a numeric vector of evaluation points.
#' @param true_g numeric vector of true g(u) values, aligned with \code{newdata}.
#' @param uvar name of the evaluation variable in \code{newdata}. If
#'   \code{NULL}, the \code{uvar} used in estimation is used.
#'
#' @return A list with components \code{metrics} (a one-row data.table),
#'   \code{pred} (the prediction data.table), and \code{resid} (true - fitted).
#'
#' @export
g_diagnostic <- function(object, ...) {
  UseMethod("g_diagnostic")
}

g_diagnostic.mfxtsemipar_cv <- function(object, newdata, true_g, uvar = NULL) {
  pred <- predict.mfxtsemipar_cv(object, newdata = newdata, uvar = uvar)
  compute_g_diagnostic(pred, true_g)
}

compute_g_diagnostic <- function(pred, true_g) {
  fit <- pred$g
  se <- pred$se

  if (length(true_g) != length(fit)) {
    stop("length(true_g) must equal the number of evaluation points.")
  }

  resid <- true_g - fit

  metrics <- data.table::data.table(
    n = length(fit),
    mse = mean(resid^2, na.rm = TRUE),
    rmse = sqrt(mean(resid^2, na.rm = TRUE)),
    mae = mean(abs(resid), na.rm = TRUE),
    corr = stats::cor(fit, true_g, use = "pairwise.complete.obs"),
    max_abs_err = max(abs(resid), na.rm = TRUE),
    mean_se = mean(se, na.rm = TRUE)
  )

  list(metrics = metrics, pred = pred, resid = resid)
}
