# Hardcoded absolute path for Rscript compatibility
source("/Users/sigma/SynologyDrive/kuanke/Downloads/jaerevision/mfxtsemipar/R/mfxtsemipar_utils.R")


#' Mixed-frequency cross-validated tensor-product semiparametric regression
#'
#' Fits a semiparametric regression where the nonparametric component is a
#' tensor-product surface. The primary variable is observed at high frequency
#' and enters inside the within-period sum; the moderator variables are observed
#' at low frequency and therefore factor out of the within-period sum. This is
#' the setting in \code{manuscript-longrun.md}, where temperature is
#' high-frequency and moderators such as long-run climate and income are
#' low-frequency.
#'
#' The efficient mixed-frequency design is
#' \code{(sum_tau splines(z1)) * splines(z2) * splines(z3)}. Cross-validation
#' searches over all combinations of interior-knot counts \code{(k1, k2, ...)}
#' so that each dimension can have a different number of knots. The
#' \code{sopt} option selects the first local minimum after sorting combinations
#' by total basis dimension.
#'
#' @param hf data.frame or data.table containing the high-frequency observations.
#'   Must include \code{id}, \code{tl}, \code{uvar_hf}, and any variables in
#'   \code{uvar_lf} that are merged from \code{lf}.
#' @param lf data.frame or data.table containing one observation per \code{id*tl}
#'   combination. Must include \code{id}, \code{tl}, \code{y}, and
#'   \code{uvar_lf}.
#' @param y name of the dependent variable (in \code{lf}).
#' @param x character vector of low-frequency covariates (in \code{lf}).
#' @param uvar_hf name of the high-frequency variable that enters the
#'   within-period sum (e.g. temperature, \code{z1}). Currently one variable.
#' @param uvar_lf character vector of low-frequency moderator variables
#'   (e.g. climate or income, \code{z2} or \code{z3}). For the bivariate models
#'   in the paper, use a single moderator at a time.
#' @param id name of the panel identifier.
#' @param tl character vector of time-level variables that define the
#'   low-frequency units (together with \code{id}).
#' @param gen name of the generated fitted-values variable.
#' @param hfcov character vector of other high-frequency covariates (in \code{hf}).
#'   They are aggregated to the low-frequency level by taking means.
#' @param cluster name of the cluster variable for robust standard errors.
#' @param type spline type: \code{"poly"}, \code{"bs"}, \code{"ms"},
#'   \code{"is"} or \code{"ibs"}. Can be a single string or a character
#'   vector of length \code{1 + length(uvar_lf)}.
#' @param winsor numeric vector of length 2, low and high percentiles for
#'   winsorizing \code{uvar_hf}; or a list with one such vector per variable in
#'   \code{c(uvar_hf, uvar_lf)}.
#' @param winsor_values logical; see \code{winsor}. Applied to all variables.
#' @param eqspace logical; if \code{TRUE}, knots are placed at equally spaced
#'   intervals instead of quantiles. Can be scalar or vector.
#' @param bknots list of numeric vectors of length 2 with boundary knots for each
#'   variable in \code{c(uvar_hf, uvar_lf)}; or \code{NULL} to use data-driven
#'   boundaries.
#' @param startp,endp numeric; optional preset minimum/maximum internal knot for
#'   each variable in \code{c(uvar_hf, uvar_lf)}. Can be scalar or vector.
#' @param maxnk integer vector; maximum number of interior knots considered for
#'   each variable in \code{c(uvar_hf, uvar_lf)}. Default is \code{5L} for all
#'   variables.
#' @param minnk integer vector; minimum number of interior knots considered for
#'   each variable in \code{c(uvar_hf, uvar_lf)}. Default is \code{2L} for all
#'   variables.
#' @param center numeric vector; centering value for each spline basis.
#' @param absorb fixed-effects specification passed to \code{fixest::feols}.
#' @param partialout \code{NULL}, \code{"all"}, or a character vector.
#' @param cvgroup name of a variable that defines CV folds. If \code{NULL},
#'   folds are generated by clustering on \code{id}.
#' @param nfold number of CV folds when \code{cvgroup} is \code{NULL}.
#' @param seed integer random seed for fold generation.
#' @param degree integer vector; polynomial degree for each variable.
#' @param keepsplines logical; if \code{TRUE}, the generated spline columns are
#'   kept in the returned fitted object.
#' @param sopt logical; if \code{TRUE}, select the first local minimum of the CV
#'   curve after sorting combinations by total basis dimension
#'   \code{K = prod(k_i)}.
#' @param bias_correct logical; if \code{TRUE} (default), compute a
#'   partitioning-based robust bias correction.
#' @param bc_degree integer vector; polynomial degree of the bias-correction
#'   spline basis for each variable. Default is \code{degree + 1}.
#' @param bc_nknots bias-correction knot specification. Either \code{NULL}
#'   (same knots as main model), an integer vector (absolute knots per
#'   dimension), or a string ending in \code{k} applied to the selected knots
#'   in each dimension.
#' @param bc_type RBC method label: \code{"bc2"} (default) or \code{"bc1"}.
#' @param bc_est RBC estimation method: \code{"stacked"} (default) or
#'   \code{"joint"}.
#' @param brep integer; number of wild-bootstrap replications for inference.
#' @param predy name of a variable for the full predicted value at low frequency.
#' @param weights name of a weight variable.
#' @param ucb logical; if \code{TRUE}, compute a uniform confidence band for
#'   the bias-corrected surface. Requires \code{bias_correct = TRUE}.
#' @param ucb_level coverage level for the UCB. Default is \code{0.95}.
#' @param ucb_sim_reps number of multivariate-normal draws. Default is
#'   \code{2000L}.
#' @param ucb_grid data.frame or data.table with columns matching
#'   \code{c(uvar_hf, uvar_lf)} giving evaluation points for the UCB. If
#'   \code{NULL}, a tensor grid of 50 equally spaced points per dimension is
#'   used.
#' @param verbose logical; print CV results.
#' @param separate logical; if \code{TRUE} (default) and \code{uvar_lf} has
#'   length greater than one, the function estimates a separate bivariate
#'   surface \code{g(z1, zj)} for each low-frequency moderator and returns a
#'   named list. If \code{FALSE}, a single trivariate surface
#'   \code{g(z1, z2, z3)} is estimated.
#'
#' @return A list with components \code{nknots}, \code{knots}, \code{cv_mse},
#'   \code{min_cv_mse}, \code{rmse}, \code{soptnk}, \code{coef}, \code{vcov},
#'   \code{coef_bc}, \code{vcov_bc}, \code{fitted}, and the full
#'   \code{fixest} estimation object. \code{cv_mse} is a data.table of
#'   cross-validated RMSE by knot-count combination.
#'
#' @examples
#' # Single bivariate surface: temperature response varying with long-run climate
#' fit_12 <- mfxtsemipar_tensor(
#'   hf = hf, lf = lf, y = "elec",
#'   uvar_hf = "z1",
#'   uvar_lf = "z2",
#'   id = "id", tl = "year",
#'   gen = "g_z1_z2",
#'   maxnk = c(8, 4), sopt = TRUE
#' )
#'
#' # Fit both (z1, z2) and (z1, z3) surfaces in one call.
#' # With \code{separate = TRUE} (the default), each moderator is handled
#' # as its own bivariate model and a named list is returned.
#' fit_list <- mfxtsemipar_tensor(
#'   hf = hf, lf = lf, y = "elec",
#'   uvar_hf = "z1",
#'   uvar_lf = c("z2", "z3"),
#'   id = "id", tl = "year",
#'   gen = "g",
#'   maxnk = c(8, 4, 3), sopt = TRUE
#' )
#' fit_12 <- fit_list[[1L]]
#' fit_13 <- fit_list[[2L]]
#'
#' @export
mfxtsemipar_tensor <- function(hf,
                               lf,
                               y,
                               x = NULL,
                               uvar_hf,
                               uvar_lf,
                               id,
                               tl,
                               gen,
                               hfcov = NULL,
                               cluster = NULL,
                               type = "bs",
                               winsor = NULL,
                               winsor_values = FALSE,
                               eqspace = FALSE,
                               bknots = NULL,
                               startp = NULL,
                               endp = NULL,
                               maxnk = 5L,
                               minnk = 2L,
                               center = NULL,
                               absorb = NULL,
                               partialout = NULL,
                               cvgroup = NULL,
                               nfold = 10L,
                               seed = NULL,
                               degree = 1L,
                               keepsplines = FALSE,
                               sopt = FALSE,
                               bias_correct = TRUE,
                               bc_degree = NULL,
                               bc_nknots = NULL,
                               bc_type = c("bc2", "bc1"),
                               bc_est = c("stacked", "joint"),
                               brep = 0L,
                               predy = NULL,
                               weights = NULL,
                               ucb = FALSE,
                               ucb_level = 0.95,
                               ucb_sim_reps = 2000L,
                               ucb_grid = NULL,
                               verbose = TRUE,
                               separate = TRUE) {

  # ------------------------------------------------------------------
  # 0. package checks
  # ------------------------------------------------------------------
  if (!requireNamespace("data.table", quietly = TRUE)) {
    stop("Package 'data.table' is required.")
  }
  if (!requireNamespace("fixest", quietly = TRUE)) {
    stop("Package 'fixest' is required.")
  }

  uvar_hf <- as.character(uvar_hf)[1L]
  uvar_lf <- as.character(uvar_lf)
  all_uvars <- c(uvar_hf, uvar_lf)
  d <- length(all_uvars)

  if (!all(type %in% c("poly", "bs", "ms", "is", "ibs"))) {
    stop("type must be one of 'poly', 'bs', 'ms', 'is', 'ibs'.")
  }
  if (any(type %in% c("ms", "is", "ibs")) &&
      !requireNamespace("splines2", quietly = TRUE)) {
    stop("Package 'splines2' is required for type 'ms', 'is' and 'ibs'.")
  }

  bc_type <- match.arg(bc_type)
  bc_est <- match.arg(bc_est)
  brep <- as.integer(brep)
  if (brep < 0L) stop("brep must be a non-negative integer.")

  # Recycle per-variable arguments to length d
  type      <- recycle_per_var(type, d, "type")
  eqspace   <- recycle_per_var(eqspace, d, "eqspace")
  maxnk     <- as.integer(recycle_per_var(maxnk, d, "maxnk"))
  minnk     <- as.integer(recycle_per_var(minnk, d, "minnk"))
  degree    <- as.integer(recycle_per_var(degree, d, "degree"))
  startp    <- recycle_per_var(startp, d, "startp", allow_null = TRUE)
  endp      <- recycle_per_var(endp, d, "endp", allow_null = TRUE)
  center    <- recycle_per_var(center, d, "center", allow_null = TRUE)
  center    <- lapply(center, function(cj) if (is.null(cj)) 0 else cj)

  if (is.null(bc_degree)) {
    bc_degree <- degree + 1L
  } else {
    bc_degree <- as.integer(recycle_per_var(bc_degree, d, "bc_degree"))
  }
  if (any(bc_degree <= degree)) {
    warning("bc_degree should be larger than degree for bias correction to be meaningful.")
  }

  # ------------------------------------------------------------------
  # 0b. multiple low-frequency moderators: fit separate bivariate surfaces
  # ------------------------------------------------------------------
  if (length(uvar_lf) > 1L && separate) {
    make_names <- function(base, vars) {
      if (is.null(base)) return(NULL)
      nm <- deparse(substitute(base))
      if (length(base) == 1L) return(paste0(base, "_", vars))
      if (length(base) == length(vars)) return(base)
      stop("'", nm, "' must have length 1 or length length(uvar_lf).")
    }
    gen_vec   <- make_names(gen, uvar_lf)
    predy_vec <- if (!is.null(predy)) make_names(predy, uvar_lf) else NULL

    results <- stats::setNames(vector("list", length(uvar_lf)),
                               paste0(uvar_hf, "_", uvar_lf))

    for (j in seq_along(uvar_lf)) {
      idx <- c(1L, j + 1L)

      args <- list(
        hf = hf, lf = lf, y = y, x = x,
        uvar_hf = uvar_hf,
        uvar_lf = uvar_lf[j],
        id = id, tl = tl,
        gen = gen_vec[j],
        hfcov = hfcov,
        cluster = cluster,
        type = type[idx],
        winsor = if (!is.null(winsor) && is.list(winsor) && length(winsor) == d) winsor[idx] else winsor,
        winsor_values = winsor_values,
        eqspace = eqspace[idx],
        bknots = if (!is.null(bknots)) bknots[idx] else NULL,
        startp = startp[idx],
        endp = endp[idx],
        maxnk = maxnk[idx],
        minnk = minnk[idx],
        center = center[idx],
        absorb = absorb,
        partialout = partialout,
        cvgroup = cvgroup,
        nfold = nfold,
        seed = seed,
        degree = degree[idx],
        keepsplines = keepsplines,
        sopt = sopt,
        bias_correct = bias_correct,
        bc_degree = if (!is.null(bc_degree)) bc_degree[idx] else NULL,
        bc_nknots = if (!is.null(bc_nknots) && is.character(bc_nknots)) bc_nknots else if (!is.null(bc_nknots)) bc_nknots[idx] else NULL,
        bc_type = bc_type,
        bc_est = bc_est,
        brep = brep,
        predy = predy_vec[j],
        weights = weights,
        ucb = ucb,
        ucb_level = ucb_level,
        ucb_sim_reps = ucb_sim_reps,
        ucb_grid = if (!is.null(ucb_grid)) ucb_grid[, c(uvar_hf, uvar_lf[j]), drop = FALSE] else NULL,
        verbose = verbose,
        separate = TRUE
      )
      results[[j]] <- do.call(mfxtsemipar_tensor, args)
    }

    class(results) <- c("mfxtsemipar_tensor_list", "list")
    return(results)
  }

  # ------------------------------------------------------------------
  # 1. basic input validation and conversion
  # ------------------------------------------------------------------
  hf <- data.table::as.data.table(hf)
  lf <- data.table::as.data.table(lf)

  if (length(tl) == 1L && is.null(names(tl))) tl <- as.character(tl)
  keys <- c(id, tl)

  miss_hf <- setdiff(c(keys, uvar_hf, hfcov), names(hf))
  if (length(miss_hf)) {
    stop("Variables not found in hf: ", paste(miss_hf, collapse = ", "))
  }
  miss_lf <- setdiff(c(keys, y, x, uvar_lf, cluster, cvgroup), names(lf))
  if (length(miss_lf)) {
    stop("Variables not found in lf: ", paste(miss_lf, collapse = ", "))
  }

  if (!is.numeric(hf[[uvar_hf]])) {
    stop("uvar_hf must be numeric.")
  }
  if (!all(vapply(uvar_lf, function(v) is.numeric(lf[[v]]), logical(1L)))) {
    stop("All uvar_lf must be numeric.")
  }

  weights_fml <- if (!is.null(weights)) stats::as.formula(paste0("~ ", weights)) else NULL

  # Merge low-frequency moderators onto hf (they are constant within id*tl)
  hf <- hf[, setdiff(names(hf), uvar_lf), with = FALSE]
  hf <- merge(hf, lf[, c(keys, uvar_lf), with = FALSE], by = keys, all.x = TRUE)

  # ------------------------------------------------------------------
  # 2. winsorize variables if requested
  # ------------------------------------------------------------------
  if (!is.null(winsor)) {
    if (is.list(winsor)) {
      if (length(winsor) != d) {
        stop("If winsor is a list, it must have one element per variable.")
      }
    } else {
      winsor <- rep(list(winsor), d)
    }
    for (j in seq_len(d)) {
      vj <- all_uvars[j]
      wj <- winsor[[j]]
      if (length(wj) != 2L) stop("Each winsor entry must be a numeric vector of length 2.")
      if (winsor_values) {
        wlow <- wj[1L]; whigh <- wj[2L]
      } else {
        src <- if (j == 1L) hf else lf
        quants <- stats::quantile(src[[vj]], probs = wj / 100,
                                  na.rm = TRUE, names = FALSE)
        wlow <- quants[1L]; whigh <- quants[2L]
      }
      if (j == 1L) {
        hf[, (vj) := pmin(pmax(get(vj), wlow), whigh)]
      } else {
        lf[, (vj) := pmin(pmax(get(vj), wlow), whigh)]
        hf[, (vj) := pmin(pmax(get(vj), wlow), whigh)]
      }
    }
  }

  # ------------------------------------------------------------------
  # 3. determine knot boundaries per variable
  # ------------------------------------------------------------------
  uvals_list <- vector("list", d)
  uvals_list[[1L]] <- hf[[uvar_hf]]
  for (j in seq_along(uvar_lf)) {
    uvals_list[[j + 1L]] <- lf[[uvar_lf[j]]]
  }
  umin_data <- vapply(uvals_list, min, numeric(1L), na.rm = TRUE)
  umax_data <- vapply(uvals_list, max, numeric(1L), na.rm = TRUE)

  if (is.null(bknots)) {
    bknots <- lapply(seq_len(d), function(j) {
      c(umin_data[j] - 0.01, umax_data[j] + 0.01)
    })
  } else {
    if (!is.list(bknots) || length(bknots) != d) {
      stop("bknots must be a list of length 1 + length(uvar_lf).")
    }
    for (j in seq_len(d)) {
      bj <- as.numeric(bknots[[j]])
      if (length(bj) != 2L || bj[1L] >= bj[2L]) {
        stop("Each bknots entry must be a strictly ascending numeric vector of length 2.")
      }
      if (umin_data[j] < bj[1L] || umax_data[j] > bj[2L]) {
        stop("Values for ", all_uvars[j], " exceed supplied boundary knots.")
      }
      bknots[[j]] <- bj
    }
  }

  if (any(minnk < 0L) || any(maxnk < minnk)) {
    stop("maxnk must be at least minnk for every variable.")
  }

  # ------------------------------------------------------------------
  # 4. generate CV groups
  # ------------------------------------------------------------------
  if (!is.null(cvgroup)) {
    lf[, .cv := as.integer(as.factor(get(cvgroup)))]
  } else {
    if (!is.null(seed)) set.seed(seed)
    ids <- unique(lf[[id]])
    folds <- sample(rep_len(seq_len(nfold), length(ids)))
    map <- data.table::data.table(.id = ids, .cv = folds)
    data.table::setnames(map, ".id", id)
    lf <- merge(lf, map, by = id, all.x = TRUE)
  }

  # ------------------------------------------------------------------
  # 5. split controls into main / partialout
  # ------------------------------------------------------------------
  all_controls <- unique(c(x, hfcov))
  if (is.null(partialout)) {
    x_main <- all_controls
    x_partial <- NULL
  } else if (identical(partialout, "all")) {
    x_main <- NULL
    x_partial <- all_controls
  } else {
    partialout <- as.character(partialout)
    x_partial <- intersect(partialout, all_controls)
    if (length(setdiff(partialout, all_controls))) {
      warning("Some partialout variables are not in x or hfcov: ",
              paste(setdiff(partialout, all_controls), collapse = ", "))
    }
    x_main <- setdiff(all_controls, x_partial)
  }

  # ------------------------------------------------------------------
  # 6. cross-validation over knot-count combinations
  # ------------------------------------------------------------------
  knot_grid_list <- lapply(seq_len(d), function(j) seq(minnk[j], maxnk[j]))
  knot_grid <- do.call(expand.grid, c(knots = knot_grid_list, stringsAsFactors = FALSE))
  colnames(knot_grid) <- paste0("nk", seq_len(d))
  knot_grid$K <- apply(knot_grid, 1L, prod)
  n_comb <- nrow(knot_grid)

  cv_rmse_vec <- rep(NA_real_, n_comb)

  for (i in seq_len(n_comb)) {
    nk_vec <- as.integer(knot_grid[i, seq_len(d)])

    B_lf <- build_lf_tensor_basis(
      hf = hf,
      lf = lf,
      keys = keys,
      uvar_hf = uvar_hf,
      uvar_lf = uvar_lf,
      nknots = nk_vec,
      type = type,
      bknots = bknots,
      degree = degree,
      center = center,
      eqspace = eqspace,
      startp = startp,
      endp = endp,
      prefix = ".Spline_"
    )
    spline_vars_cv <- setdiff(names(B_lf), keys)

    lf_est_cv <- merge(lf, B_lf, by = keys, all.x = TRUE)

    cv_rmse_vec[i] <- rmse_cv(
      data = lf_est_cv,
      y = y,
      varlist = c(spline_vars_cv, x_main),
      partialout = x_partial,
      absorb = absorb,
      cluster = cluster,
      weights_fml = weights_fml,
      cvvar = ".cv"
    )
  }

  cv_mse <- data.table::as.data.table(knot_grid)
  cv_mse[, cv_rmse := cv_rmse_vec]

  # select optimal knots
  minpos <- which.min(cv_rmse_vec)
  nknots <- as.integer(knot_grid[minpos, seq_len(d)])
  soptnk <- nknots

  if (sopt) {
    ord <- order(cv_mse$K)
    cv_sorted <- cv_mse[ord, ]
    sopt_idx_local <- 1L
    for (r in seq_len(nrow(cv_sorted))) {
      if (r == 1L || cv_sorted$cv_rmse[r] < cv_sorted$cv_rmse[r - 1L]) {
        sopt_idx_local <- r
      } else {
        break
      }
    }
    sopt_idx <- ord[sopt_idx_local]
    soptnk <- as.integer(knot_grid[sopt_idx, seq_len(d)])
    nknots <- soptnk
    minpos <- sopt_idx
  }

  min_cv_mse <- cv_rmse_vec[minpos]

  # Parse bias-correction knots
  bc_nk_vec <- parse_bc_nknots_tensor(bc_nknots, nknots)

  if (verbose) {
    cat("\nCross-validation RMSE (for knot selection)\n")
    print(cv_mse, row.names = FALSE)
    cat("\nSelected knots:", paste(nknots, collapse = " x "), "\n")
    if (sopt) cat("S-opt knots:", paste(soptnk, collapse = " x "), "\n")
  }

  # ------------------------------------------------------------------
  # 7. final estimation with optimal knots
  # ------------------------------------------------------------------
  B_lf <- build_lf_tensor_basis(
    hf = hf,
    lf = lf,
    keys = keys,
    uvar_hf = uvar_hf,
    uvar_lf = uvar_lf,
    nknots = nknots,
    type = type,
    bknots = bknots,
    degree = degree,
    center = center,
    eqspace = eqspace,
    startp = startp,
    endp = endp,
    prefix = ".Spline_"
  )
  spline_vars <- setdiff(names(B_lf), keys)
  spline_cmd <- attr(B_lf, "call")

  lf_est <- merge(lf, B_lf, by = keys, all.x = TRUE)

  cluster_fml <- if (!is.null(cluster)) stats::as.formula(paste0("~ ", cluster)) else NULL

  # ------------------------------------------------------------------
  # 8. main regression
  # ------------------------------------------------------------------
  fml_main <- build_formula(y = y, varlist = c(spline_vars, x_main),
                            partialout = x_partial, absorb = absorb)
  est_main <- fixest::feols(fml_main, data = lf_est, cluster = cluster_fml,
                            weights = weights_fml, warn = FALSE, notes = FALSE)
  b_main <- stats::coef(est_main)
  V_main <- stats::vcov(est_main)
  retained_spline_main <- intersect(names(b_main), spline_vars)

  # ------------------------------------------------------------------
  # 9. robust bias correction
  # ------------------------------------------------------------------
  bc_knots <- NULL
  bc_spline_vars <- NULL
  bc_spline_cmd <- NULL
  bc_G0 <- NULL
  bc_M <- NULL
  retained_bc <- NULL
  est_stack <- NULL
  b_bc <- NULL
  V_bc <- NULL
  V_bc1_boot <- NULL
  V_bc2_boot <- NULL

  if (bias_correct) {
    bc_knots <- lapply(seq_len(d), function(j) {
      if (is.na(bc_nk_vec[j])) {
        attr(B_lf, "knots")[[j]]
      } else {
        src <- if (j == 1L) hf[[uvar_hf]] else lf[[uvar_lf[j - 1L]]]
        gennknots(src, nknots = bc_nk_vec[j], eqspace = eqspace[j],
                  startp = startp[[j]], endp = endp[[j]])
      }
    })

    Bc_lf <- build_lf_tensor_basis_from_knots(
      hf = hf,
      lf = lf,
      keys = keys,
      uvar_hf = uvar_hf,
      uvar_lf = uvar_lf,
      knots = bc_knots,
      type = type,
      bknots = bknots,
      degree = bc_degree,
      center = center,
      prefix = ".SplineBC_"
    )
    bc_spline_vars <- setdiff(names(Bc_lf), keys)
    bc_spline_cmd <- attr(Bc_lf, "call")

    lf_est <- merge(lf_est, Bc_lf, by = keys, all.x = TRUE)

    B_lf_mat <- as.matrix(lf_est[, retained_spline_main, with = FALSE])
    Bc_lf_mat <- as.matrix(lf_est[, bc_spline_vars, with = FALSE])
    wvec <- if (!is.null(weights)) lf_est[[weights]] else rep(1, nrow(lf_est))
    cc <- complete.cases(B_lf_mat, Bc_lf_mat, wvec)
    B_lf_mat <- B_lf_mat[cc, , drop = FALSE]
    Bc_lf_mat <- Bc_lf_mat[cc, , drop = FALSE]
    wvec <- wvec[cc]
    sw <- sqrt(wvec)
    B_lf_w <- B_lf_mat * sw
    Bc_lf_w <- Bc_lf_mat * sw
    bc_G0_full <- solve(crossprod(B_lf_w) / sum(wvec))
    bc_M_full <- crossprod(B_lf_w, Bc_lf_w) / sum(wvec)
    colnames(bc_M_full) <- bc_spline_vars

    if (bc_est == "stacked") {
      lf_stack <- data.table::rbindlist(list(lf_est, lf_est))
      lf_stack[, .eq := rep(c(0L, 1L), each = nrow(lf_est))]

      make_eq_col <- function(var, eq) {
        ifelse(lf_stack$.eq == eq, lf_stack[[var]], 0)
      }

      eq0_vars <- character()
      eq1_vars <- character()

      for (var in spline_vars) {
        v0 <- paste0(var, "_eq0")
        lf_stack[, (v0) := make_eq_col(var, 0L)]
        eq0_vars <- c(eq0_vars, v0)
      }
      for (var in bc_spline_vars) {
        v1 <- paste0(var, "_eq1")
        lf_stack[, (v1) := make_eq_col(var, 1L)]
        eq1_vars <- c(eq1_vars, v1)
      }

      all_controls <- unique(c(x_main, x_partial))
      for (var in all_controls) {
        v0 <- paste0(var, "_eq0")
        v1 <- paste0(var, "_eq1")
        lf_stack[, (v0) := make_eq_col(var, 0L)]
        lf_stack[, (v1) := make_eq_col(var, 1L)]
        eq0_vars <- c(eq0_vars, v0)
        eq1_vars <- c(eq1_vars, v1)
      }

      active_vars <- c(eq0_vars, eq1_vars)
      rhs <- paste(active_vars, collapse = " + ")
      fml_stack <- paste0(y, " ~ ", rhs)

      if (!is.null(absorb)) {
        if (inherits(absorb, "formula")) {
          abs_txt <- paste(deparse(absorb), collapse = "")
          abs_txt <- sub("^\\s*~\\s*", "", abs_txt)
        } else {
          abs_txt <- paste(absorb, collapse = " + ")
        }
        fml_stack <- paste0(fml_stack, " | ", abs_txt, "^.eq")
      } else {
        fml_stack <- paste0(fml_stack, " | .eq")
      }
      fml_stack <- stats::as.formula(fml_stack)

      est_stack <- fixest::feols(fml_stack, data = lf_stack, cluster = cluster_fml,
                                 weights = weights_fml, warn = FALSE, notes = FALSE)

      b_stack <- stats::coef(est_stack)
      nm0 <- names(b_stack)
      main_coef_names <- paste0(retained_spline_main, "_eq0")
      bc_coef_names <- paste0(bc_spline_vars, "_eq1")
      retained_spline_stack <- intersect(nm0, main_coef_names)
      retained_bc_stack <- intersect(nm0, bc_coef_names)

      retained_spline <- sub("_eq0$", "", retained_spline_stack)
      retained_bc <- sub("_eq1$", "", retained_bc_stack)
      names(b_stack)[nm0 %in% retained_spline_stack] <- retained_spline
      names(b_stack)[nm0 %in% retained_bc_stack] <- retained_bc

      b_main <- b_stack[retained_spline]
      V_stack <- stats::vcov(est_stack)
      V_main <- V_stack[retained_spline_stack, retained_spline_stack, drop = FALSE]
      rownames(V_main) <- colnames(V_main) <- retained_spline

      all_retained <- c(retained_spline, retained_bc)
      all_retained_stack <- c(retained_spline_stack, retained_bc_stack)
      b_bc <- b_stack[all_retained]
      V_bc <- V_stack[all_retained_stack, all_retained_stack, drop = FALSE]
      rownames(V_bc) <- colnames(V_bc) <- all_retained

      bc_G0 <- bc_G0_full
      bc_M <- bc_M_full[, retained_bc, drop = FALSE]
    } else {
      P_full <- bc_G0_full %*% bc_M_full
      Bc_orth_lf <- Bc_lf_mat - B_lf_mat %*% P_full

      bc_orth_vars <- paste0(bc_spline_vars, "_orth")
      for (j in seq_along(bc_orth_vars)) {
        data.table::set(lf_est, j = bc_orth_vars[j], value = Bc_orth_lf[, j])
      }

      varlist_joint <- c(retained_spline_main, bc_orth_vars, x_main)
      fml_joint <- build_formula(y = y, varlist = varlist_joint,
                                 partialout = x_partial, absorb = absorb)
      est_stack <- fixest::feols(fml_joint, data = lf_est, cluster = cluster_fml,
                                 weights = weights_fml, warn = FALSE, notes = FALSE)

      b_joint <- stats::coef(est_stack)
      V_joint <- stats::vcov(est_stack)

      retained_spline_stack <- intersect(names(b_joint), retained_spline_main)
      retained_bc_stack <- intersect(names(b_joint), bc_orth_vars)

      retained_spline <- retained_spline_stack
      retained_bc <- sub("_orth$", "", retained_bc_stack)

      beta_joint <- b_joint[retained_spline_stack]
      gamma_orth <- b_joint[retained_bc_stack]
      names(beta_joint) <- retained_spline
      names(gamma_orth) <- retained_bc

      b_bc <- c(beta_joint, gamma_orth)

      idx_orth <- c(retained_spline_stack, retained_bc_stack)
      V_bc <- V_joint[idx_orth, idx_orth, drop = FALSE]
      rownames(V_bc) <- colnames(V_bc) <- c(retained_spline, retained_bc)

      bc_G0 <- bc_G0_full
      bc_M <- bc_M_full[, retained_bc, drop = FALSE]
    }
  }

  est <- if (bias_correct) est_stack else est_main
  b <- b_main
  V <- V_main

  info <- fixest::fitstat(est, type = c("ll", "aic", "bic", "n"))
  rmse <- sqrt(mean(stats::residuals(est_main)^2, na.rm = TRUE))

  # ------------------------------------------------------------------
  # 10. prediction at high-frequency evaluation points
  # ------------------------------------------------------------------
  B_hf <- build_hf_tensor_basis_from_knots(
    hf = hf,
    uvar_hf = uvar_hf,
    uvar_lf = uvar_lf,
    knots = attr(B_lf, "knots"),
    type = type,
    bknots = bknots,
    degree = degree,
    center = center,
    prefix = ".Spline_"
  )

  retained_spline <- intersect(names(b), spline_vars)
  if (length(retained_spline) == 0L) {
    stop("All spline coefficients were dropped; check collinearity.")
  }
  B_hf_retained <- B_hf[, retained_spline, drop = FALSE]

  b_spline <- b[retained_spline]
  fitted_vals_raw <- as.numeric(B_hf_retained %*% b_spline)
  V_raw <- V[retained_spline, retained_spline, drop = FALSE]
  se_vals_raw <- sqrt(pmax(0, rowSums((B_hf_retained %*% V_raw) * B_hf_retained)))

  fitted_vals_bc <- fitted_vals_raw
  se_vals_bc <- se_vals_raw

  if (bias_correct) {
    Bc_hf <- build_hf_tensor_basis_from_knots(
      hf = hf,
      uvar_hf = uvar_hf,
      uvar_lf = uvar_lf,
      knots = bc_knots,
      type = type,
      bknots = bknots,
      degree = bc_degree,
      center = center,
      prefix = ".SplineBC_"
    )

    retained_bc <- intersect(names(b_bc), bc_spline_vars)
    if (length(retained_bc) == 0L) {
      stop("All bias-correction spline coefficients were dropped; check collinearity.")
    }
    Bc_hf_retained <- Bc_hf[, retained_bc, drop = FALSE]

    all_retained <- c(retained_spline, retained_bc)
    b_joint <- b_bc[all_retained]
    V_joint <- V_bc[all_retained, all_retained, drop = FALSE]

    fitted_vals_bc1 <- as.numeric(Bc_hf_retained %*% b_joint[retained_bc])
    se_vals_bc1 <- sqrt(pmax(0, rowSums((Bc_hf_retained %*%
                                          V_joint[retained_bc, retained_bc, drop = FALSE]) * Bc_hf_retained)))

    proj_main <- bc_G0 %*% bc_M[, retained_bc, drop = FALSE]
    w_bc2 <- cbind(B_hf_retained, Bc_hf_retained - B_hf_retained %*% proj_main)

    fitted_vals_bc2 <- as.numeric(w_bc2 %*% b_joint)
    se_vals_bc2 <- sqrt(pmax(0, rowSums((w_bc2 %*% V_joint) * w_bc2)))

    if (bc_est == "joint") {
      fitted_vals_bc1 <- fitted_vals_bc2
      se_vals_bc1 <- se_vals_bc2
    }

    if (bc_type == "bc1") {
      fitted_vals_bc <- fitted_vals_bc1
      se_vals_bc <- se_vals_bc1
    } else {
      fitted_vals_bc <- fitted_vals_bc2
      se_vals_bc <- se_vals_bc2
    }
  }

  out_dt <- data.table::copy(hf[, c(keys, uvar_hf, uvar_lf), with = FALSE])
  out_dt[, (paste0(gen, "_raw")) := fitted_vals_raw]
  out_dt[, (gen) := fitted_vals_bc]
  out_dt[, (paste0(gen, "_se")) := se_vals_raw]
  if (bias_correct) {
    out_dt[, (paste0(gen, "_bc1")) := fitted_vals_bc1]
    out_dt[, (paste0(gen, "_bc1_se")) := se_vals_bc1]
    out_dt[, (paste0(gen, "_bc_se")) := se_vals_bc]
  }

  if (keepsplines) {
    for (j in seq_along(spline_vars)) {
      out_dt[, (spline_vars[j]) := B_hf[, j]]
    }
  }

  # ------------------------------------------------------------------
  # 11. predy at low frequency
  # ------------------------------------------------------------------
  predy_dt <- NULL
  if (!is.null(predy)) {
    lf_est[, (predy) := stats::predict(est_main, type = "response")]
    predy_dt <- lf_est[, c(keys, predy), with = FALSE]
    out_dt <- merge(out_dt, predy_dt, by = keys, all.x = TRUE)
  }

  # ------------------------------------------------------------------
  # 12. return
  # ------------------------------------------------------------------
  result <- list(
    uvar_hf = uvar_hf,
    uvar_lf = uvar_lf,
    soptnk = soptnk,
    nknots = nknots,
    knots = attr(B_lf, "knots"),
    bknots = bknots,
    min_cv_mse = min_cv_mse,
    cv_mse = cv_mse,
    rmse = rmse,
    splinecmd = spline_cmd,
    type = type,
    degree = degree,
    center = vapply(center, function(cj) cj, numeric(1L)),
    id = id,
    tl = tl,
    coef = b,
    coef_bc = if (bias_correct) b_bc else NULL,
    vcov = V,
    vcov_bc = if (bias_correct) V_bc else NULL,
    info = info,
    fitted = out_dt,
    predy = predy_dt,
    estimation = est,
    bc_type = if (bias_correct) bc_type else NULL,
    bc_est = if (bias_correct) bc_est else NULL,
    bc_degree = if (bias_correct) bc_degree else NULL,
    bc_nknots = if (bias_correct) bc_nk_vec else NULL,
    bc_knots = if (bias_correct) bc_knots else NULL,
    bc_splinecmd = bc_spline_cmd,
    bc_G0 = if (bias_correct) bc_G0 else NULL,
    bc_M = if (bias_correct) bc_M else NULL,
    retained_spline = retained_spline_main,
    bc_retained_bc = retained_bc,
    call = match.call()
  )

  class(result) <- c("mfxtsemipar_tensor", "list")

  # ------------------------------------------------------------------
  # 13. uniform confidence band
  # ------------------------------------------------------------------
  if (ucb) {
    if (!bias_correct) {
      warning("ucb = TRUE requires bias_correct = TRUE; UCB computation skipped.",
              call. = FALSE)
    } else {
      ucb_res <- compute_ucb_tensor(result,
                                    newdata = ucb_grid,
                                    uvar_hf = uvar_hf,
                                    uvar_lf = uvar_lf,
                                    level = ucb_level,
                                    sim_reps = ucb_sim_reps)
      crit <- ucb_res$crit
      ucb_dt <- ucb_res$grid
      ucb_dt[, (paste0(gen, "_lb")) := g - crit * se]
      ucb_dt[, (paste0(gen, "_ub")) := g + crit * se]

      result$ucb <- list(
        grid = ucb_dt,
        crit = crit,
        level = ucb_level,
        sim_reps = ucb_sim_reps
      )
    }
  }

  return(result)
}


# ==============================================================================
# Helpers for per-variable recycling
# ==============================================================================
recycle_per_var <- function(x, d, name, allow_null = FALSE) {
  if (allow_null && is.null(x)) return(rep(list(NULL), d))
  if (is.null(x)) stop("'", name, "' cannot be NULL.")
  if (length(x) == 1L || (is.list(x) && length(x) == 1L)) {
    return(rep(x, d))
  }
  if (length(x) != d) {
    stop("'", name, "' must have length 1 or length ", d, ".")
  }
  return(x)
}


# ==============================================================================
# Helper: build low-frequency tensor-product basis
# B_lf = (sum_tau B_hf(z1)) * B_lf(z2) * B_lf(z3)
# ==============================================================================
build_lf_tensor_basis <- function(hf, lf, keys, uvar_hf, uvar_lf, nknots, type,
                                  bknots, degree, center, eqspace,
                                  startp, endp, prefix = ".Spline_") {
  d <- 1L + length(uvar_lf)

  # High-frequency z1 splines, aggregated to low frequency
  knots1 <- gennknots(hf[[uvar_hf]], nknots = nknots[1L],
                      eqspace = eqspace[1L],
                      startp = startp[[1L]], endp = endp[[1L]])
  sp1 <- make_splines(
    x = hf[[uvar_hf]],
    type = type[1L],
    knots = knots1,
    bknots = bknots[[1L]],
    degree = degree[1L],
    center = center[[1L]],
    intercept = TRUE,
    prefix = paste0(prefix, "1_")
  )
  add_splines_to_hf(hf, sp1$matrix, sp1$names)

  B1_lf <- hf[, lapply(.SD, sum, na.rm = TRUE), by = keys, .SDcols = sp1$names]
  hf[, (sp1$names) := NULL]

  # Low-frequency moderator splines
  bases <- list(B1_lf[, setdiff(names(B1_lf), keys), with = FALSE])
  knots_all <- list(knots1)

  for (j in seq_along(uvar_lf)) {
    jj <- j + 1L
    knots_j <- gennknots(lf[[uvar_lf[j]]], nknots = nknots[jj],
                         eqspace = eqspace[jj],
                         startp = startp[[jj]], endp = endp[[jj]])
    sp_j <- make_splines(
      x = lf[[uvar_lf[j]]],
      type = type[jj],
      knots = knots_j,
      bknots = bknots[[jj]],
      degree = degree[jj],
      center = center[[jj]],
      intercept = TRUE,
      prefix = paste0(prefix, jj, "_")
    )
    B_lf_j <- data.table::as.data.table(sp_j$matrix)
    B_lf_j[, (keys) := lf[, keys, with = FALSE]]
    bases[[jj]] <- B_lf_j[, setdiff(names(B_lf_j), keys), with = FALSE]
    knots_all[[jj]] <- knots_j
  }

  # Merge all bases by keys
  B_lf <- B1_lf
  for (j in seq(2L, d)) {
    B_lf <- merge(B_lf, cbind(lf[, keys, with = FALSE], bases[[j]]),
                  by = keys, all.x = TRUE)
  }

  # Tensor product row-wise
  mat_list <- lapply(bases, function(bj) as.matrix(bj))
  B_tensor <- mat_list[[1L]]
  for (j in seq(2L, d)) {
    B_tensor <- khatri_rao(B_tensor, mat_list[[j]])
  }

  dim_idx <- expand.grid(lapply(seq_len(d), function(j) seq_len(ncol(bases[[j]]))))
  vars <- apply(dim_idx, 1L, function(idx) paste0(prefix, paste(idx, collapse = "_")))
  colnames(B_tensor) <- vars

  out <- data.table::as.data.table(B_tensor)
  out[, (keys) := B_lf[, keys, with = FALSE]]
  data.table::setcolorder(out, c(keys, vars))

  call_txt <- paste0(
    "LF tensor-product ", paste(type, collapse = "/"),
    " splines; knots per dim: ", paste(nknots, collapse = " x "),
    "; total K = ", ncol(B_tensor)
  )
  attr(out, "call") <- call_txt
  attr(out, "knots") <- knots_all
  out
}


# ==============================================================================
# Helper: build LF tensor basis from pre-specified knots
# ==============================================================================
build_lf_tensor_basis_from_knots <- function(hf, lf, keys, uvar_hf, uvar_lf,
                                             knots, type, bknots, degree,
                                             center, prefix = ".Spline_") {
  d <- 1L + length(uvar_lf)

  sp1 <- make_splines(
    x = hf[[uvar_hf]],
    type = type[1L],
    knots = knots[[1L]],
    bknots = bknots[[1L]],
    degree = degree[1L],
    center = center[[1L]],
    intercept = TRUE,
    prefix = paste0(prefix, "1_")
  )
  add_splines_to_hf(hf, sp1$matrix, sp1$names)
  B1_lf <- hf[, lapply(.SD, sum, na.rm = TRUE), by = keys, .SDcols = sp1$names]
  hf[, (sp1$names) := NULL]

  bases <- list(B1_lf[, setdiff(names(B1_lf), keys), with = FALSE])

  for (j in seq_along(uvar_lf)) {
    jj <- j + 1L
    sp_j <- make_splines(
      x = lf[[uvar_lf[j]]],
      type = type[jj],
      knots = knots[[jj]],
      bknots = bknots[[jj]],
      degree = degree[jj],
      center = center[[jj]],
      intercept = TRUE,
      prefix = paste0(prefix, jj, "_")
    )
    B_lf_j <- data.table::as.data.table(sp_j$matrix)
    B_lf_j[, (keys) := lf[, keys, with = FALSE]]
    bases[[jj]] <- B_lf_j[, setdiff(names(B_lf_j), keys), with = FALSE]
  }

  B_lf <- B1_lf
  for (j in seq(2L, d)) {
    B_lf <- merge(B_lf, cbind(lf[, keys, with = FALSE], bases[[j]]),
                  by = keys, all.x = TRUE)
  }

  mat_list <- lapply(bases, function(bj) as.matrix(bj))
  B_tensor <- mat_list[[1L]]
  for (j in seq(2L, d)) {
    B_tensor <- khatri_rao(B_tensor, mat_list[[j]])
  }

  dim_idx <- expand.grid(lapply(seq_len(d), function(j) seq_len(ncol(bases[[j]]))))
  vars <- apply(dim_idx, 1L, function(idx) paste0(prefix, paste(idx, collapse = "_")))
  colnames(B_tensor) <- vars

  out <- data.table::as.data.table(B_tensor)
  out[, (keys) := B_lf[, keys, with = FALSE]]
  data.table::setcolorder(out, c(keys, vars))
  out
}


# ==============================================================================
# Helper: build high-frequency tensor-product basis from knots
# B_hf = B_hf(z1) * B_lf(z2 replicated) * B_lf(z3 replicated)
# ==============================================================================
build_hf_tensor_basis_from_knots <- function(hf, uvar_hf, uvar_lf, knots, type,
                                             bknots, degree, center,
                                             prefix = ".Spline_") {
  d <- 1L + length(uvar_lf)

  sp1 <- make_splines(
    x = hf[[uvar_hf]],
    type = type[1L],
    knots = knots[[1L]],
    bknots = bknots[[1L]],
    degree = degree[1L],
    center = center[[1L]],
    intercept = TRUE,
    prefix = paste0(prefix, "1_")
  )

  bases <- list(sp1$matrix)

  for (j in seq_along(uvar_lf)) {
    jj <- j + 1L
    sp_j <- make_splines(
      x = hf[[uvar_lf[j]]],
      type = type[jj],
      knots = knots[[jj]],
      bknots = bknots[[jj]],
      degree = degree[jj],
      center = center[[jj]],
      intercept = TRUE,
      prefix = paste0(prefix, jj, "_")
    )
    bases[[jj]] <- sp_j$matrix
  }

  B_tensor <- bases[[1L]]
  for (j in seq(2L, d)) {
    B_tensor <- khatri_rao(B_tensor, bases[[j]])
  }

  dim_idx <- expand.grid(lapply(seq_len(d), function(j) seq_len(ncol(bases[[j]]))))
  vars <- apply(dim_idx, 1L, function(idx) paste0(prefix, paste(idx, collapse = "_")))
  colnames(B_tensor) <- vars

  B_tensor
}


# ==============================================================================
# Helper: row-wise Khatri-Rao product
# ==============================================================================
khatri_rao <- function(A, B) {
  n <- nrow(A)
  if (nrow(B) != n) stop("Matrices must have the same number of rows.")
  p <- ncol(A)
  q <- ncol(B)
  out <- matrix(0, nrow = n, ncol = p * q)
  for (i in seq_len(n)) {
    out[i, ] <- as.numeric(outer(A[i, ], B[i, ]))
  }
  out
}


# ==============================================================================
# Helper: parse bc_nknots for tensor product
# ==============================================================================
parse_bc_nknots_tensor <- function(bc_nknots, nknots) {
  d <- length(nknots)
  if (is.null(bc_nknots)) return(rep(NA_integer_, d))

  if (is.character(bc_nknots) && length(bc_nknots) == 1L &&
      grepl("k$", bc_nknots, ignore.case = TRUE)) {
    mult <- suppressWarnings(as.numeric(sub("k$", "", bc_nknots, ignore.case = TRUE)))
    if (!is.finite(mult) || mult <= 0) stop("bc_nknots multiplier must be positive.")
    return(pmax(1L, as.integer(round(nknots * mult))))
  }

  if (is.numeric(bc_nknots)) {
    if (length(bc_nknots) == 1L) {
      bc_nknots <- rep(as.integer(round(bc_nknots)), d)
    }
    if (length(bc_nknots) != d) {
      stop("bc_nknots must have length 1 or length 1 + length(uvar_lf).")
    }
    return(as.integer(round(bc_nknots)))
  }

  stop("bc_nknots must be NULL, a positive integer (vector), or a string like '1.5k'.")
}


# ==============================================================================
# Helper: compute uniform confidence band
# ==============================================================================
compute_ucb_tensor <- function(object,
                               newdata,
                               uvar_hf,
                               uvar_lf,
                               level = 0.95,
                               sim_reps = 2000L) {
  if (!inherits(object, "mfxtsemipar_tensor")) {
    stop("object must be of class 'mfxtsemipar_tensor'.")
  }
  if (is.null(object$coef_bc)) {
    stop("UCB requires bias_correct = TRUE.")
  }

  all_uvars <- c(uvar_hf, uvar_lf)
  d <- length(all_uvars)

  if (is.null(newdata)) {
    grid_list <- lapply(seq_len(d), function(j) {
      uj <- if (j == 1L) object$fitted[[uvar_hf]] else object$fitted[[uvar_lf[j - 1L]]]
      seq(min(uj, na.rm = TRUE), max(uj, na.rm = TRUE), length.out = 50L)
    })
    newdata <- do.call(expand.grid, c(grid_list, stringsAsFactors = FALSE))
    names(newdata) <- all_uvars
  }
  newdata <- data.table::as.data.table(newdata)

  B <- build_hf_tensor_basis_from_knots(
    hf = newdata,
    uvar_hf = uvar_hf,
    uvar_lf = uvar_lf,
    knots = object$knots,
    type = object$type,
    bknots = object$bknots,
    degree = object$degree,
    center = as.list(object$center),
    prefix = ".Spline_"
  )
  spline_vars <- colnames(B)

  retained <- intersect(names(object$coef), spline_vars)
  if (length(retained) == 0L) stop("No spline coefficients available for UCB.")
  B_retained <- B[, retained, drop = FALSE]

  retained_bc <- object$bc_retained_bc

  Bc <- build_hf_tensor_basis_from_knots(
    hf = newdata,
    uvar_hf = uvar_hf,
    uvar_lf = uvar_lf,
    knots = object$bc_knots,
    type = object$type,
    bknots = object$bknots,
    degree = object$bc_degree,
    center = as.list(object$center),
    prefix = ".SplineBC_"
  )
  Bc_retained <- Bc[, retained_bc, drop = FALSE]

  all_retained <- c(retained, retained_bc)
  b_joint <- object$coef_bc[all_retained]
  V_joint <- object$vcov_bc[all_retained, all_retained, drop = FALSE]

  bc_type <- object$bc_type
  if (bc_type == "bc1") {
    w <- cbind(matrix(0, nrow = nrow(B_retained), ncol = length(retained)),
               Bc_retained)
  } else {
    proj_main <- object$bc_G0 %*% object$bc_M[, retained_bc, drop = FALSE]
    Bc_orth_retained <- Bc_retained - B_retained %*% proj_main
    w <- cbind(B_retained, Bc_orth_retained)
  }

  y <- as.numeric(w %*% b_joint)
  se <- sqrt(pmax(0, rowSums((w %*% V_joint) * w)))

  draws <- simulate_mvnorm(sim_reps, V_joint)
  deviations <- draws %*% t(w)

  se_safe <- pmax(se, .Machine$double.eps)
  t_stats <- apply(abs(deviations) / matrix(se_safe, nrow = sim_reps,
                                            ncol = length(se_safe), byrow = TRUE),
                   1, max)
  crit <- as.numeric(stats::quantile(t_stats, probs = level, na.rm = TRUE))

  out <- data.table::copy(newdata)
  out[, g := y]
  out[, se := se]
  out[, lb := g - crit * se]
  out[, ub := g + crit * se]

  list(grid = out, crit = crit, level = level, sim_reps = sim_reps)
}


# ==============================================================================
# Print and predict methods
# ==============================================================================
#' @export
print.mfxtsemipar_tensor <- function(x, ...) {
  cat("Mixed-frequency tensor-product semiparametric regression\n")
  cat("  High-frequency variable: ", x$uvar_hf, "\n", sep = "")
  cat("  Low-frequency moderator(s): ", paste(x$uvar_lf, collapse = ", "), "\n", sep = "")
  cat("  Selected knots: ", paste(x$nknots, collapse = " x "), "\n", sep = "")
  cat("  Minimum CV RMSE: ", round(x$min_cv_mse, 6), "\n", sep = "")
  cat("  Final fit RMSE: ", round(x$rmse, 6), "\n", sep = "")
  cat("  Simple optimal knots: ", paste(x$soptnk, collapse = " x "), "\n", sep = "")
  bc_type <- if (!is.null(x$bc_type)) paste0(x$bc_type, " (degree ",
                                              paste(x$bc_degree, collapse = "/"), ")") else "none"
  cat("  Bias correction: ", bc_type, "\n", sep = "")
  cat("\nCV RMSE by knot combination:\n")
  print(x$cv_mse, row.names = FALSE)
  invisible(x)
}


#' @export
print.mfxtsemipar_tensor_list <- function(x, ...) {
  cat("Mixed-frequency tensor-product regression list\n")
  cat("  Number of bivariate surfaces: ", length(x), "\n", sep = "")
  for (i in seq_along(x)) {
    nm <- names(x)[i]
    cat("\n[[", i, "]] ", nm, "\n", sep = "")
    cat("  Selected knots: ", paste(x[[i]]$nknots, collapse = " x "),
        "; CV RMSE: ", round(x[[i]]$min_cv_mse, 6),
        "; Fit RMSE: ", round(x[[i]]$rmse, 6), "\n", sep = "")
  }
  invisible(x)
}


#' @export
predict.mfxtsemipar_tensor <- function(object, newdata,
                                       uvar_hf = NULL, uvar_lf = NULL,
                                       bias_correct = TRUE, ...) {
  if (!inherits(object, "mfxtsemipar_tensor")) {
    stop("object must be of class 'mfxtsemipar_tensor'.")
  }
  if (is.null(uvar_hf)) uvar_hf <- object$uvar_hf
  if (is.null(uvar_lf)) uvar_lf <- object$uvar_lf
  all_uvars <- c(uvar_hf, uvar_lf)

  newdata <- data.table::as.data.table(newdata)
  if (!all(all_uvars %in% names(newdata))) {
    stop("All uvars must be present in newdata.")
  }

  B <- build_hf_tensor_basis_from_knots(
    hf = newdata,
    uvar_hf = uvar_hf,
    uvar_lf = uvar_lf,
    knots = object$knots,
    type = object$type,
    bknots = object$bknots,
    degree = object$degree,
    center = as.list(object$center),
    prefix = ".Spline_"
  )
  spline_vars <- colnames(B)

  retained <- intersect(names(object$coef), spline_vars)
  if (length(retained) == 0L) stop("No spline coefficients available for prediction.")
  B_retained <- B[, retained, drop = FALSE]

  if (bias_correct && !is.null(object$bc_type)) {
    retained_bc <- object$bc_retained_bc
    Bc <- build_hf_tensor_basis_from_knots(
      hf = newdata,
      uvar_hf = uvar_hf,
      uvar_lf = uvar_lf,
      knots = object$bc_knots,
      type = object$type,
      bknots = object$bknots,
      degree = object$bc_degree,
      center = as.list(object$center),
      prefix = ".SplineBC_"
    )
    Bc_retained <- Bc[, retained_bc, drop = FALSE]

    all_retained <- c(retained, retained_bc)
    b_joint <- object$coef_bc[all_retained]
    V_joint <- object$vcov_bc[all_retained, all_retained, drop = FALSE]

    if (object$bc_type == "bc1") {
      w <- cbind(matrix(0, nrow = nrow(B_retained), ncol = length(retained)),
                 Bc_retained)
    } else {
      proj_main <- object$bc_G0 %*% object$bc_M[, retained_bc, drop = FALSE]
      Bc_orth_retained <- Bc_retained - B_retained %*% proj_main
      w <- cbind(B_retained, Bc_orth_retained)
    }

    fit <- as.numeric(w %*% b_joint)
    se <- sqrt(pmax(0, rowSums((w %*% V_joint) * w)))
  } else {
    b <- object$coef[retained]
    fit <- as.numeric(B_retained %*% b)
    V <- object$vcov[retained, retained, drop = FALSE]
    se <- sqrt(pmax(0, rowSums((B_retained %*% V) * B_retained)))
  }

  out <- data.table::copy(newdata)
  out[, g := fit]
  out[, se := se]
  out
}
