#' Mixed-frequency cross-validated semiparametric regression with robust bias correction
#'
#' R implementation of Stata's \code{mfxtsemipar_cv}. Fits a semiparametric
#' regression where the nonparametric component is evaluated at high frequency
#' and then aggregated to a low frequency before estimation. Cross-validation is
#' used to select the number of knots. When \code{bias_correct = TRUE}, the
#' nonparametric component is bias-corrected using a partitioning-based robust
#' bias correction (RBC) following Cattaneo, Farrell and Feng (2020). The
#' standard errors account for the joint estimation of the main and
#' bias-correction spline bases.
#'
#' @param hf data.frame or data.table containing the high-frequency observations.
#'   Must include \code{id}, \code{tl} and \code{uvar}.
#' @param lf data.frame or data.table containing one observation per \code{id*tl}
#'   combination. Must include \code{id}, \code{tl} and \code{y}.
#' @param y name of the dependent variable (in \code{lf}).
#' @param x character vector of low-frequency covariates (in \code{lf}).
#' @param uvar name of the variable used for the semiparametric transformation
#'   (in \code{hf}).
#' @param id name of the panel identifier.
#' @param tl character vector of time-level variables that define the
#'   low-frequency units (together with \code{id}).
#' @param gen name of the generated fitted-values variable.
#' @param hfcov character vector of high-frequency covariates (in \code{hf}).
#'   They are aggregated to the low-frequency level by taking means.
#' @param cluster name of the cluster variable for robust standard errors.
#' @param type spline type: \code{"poly"}, \code{"bs"}, \code{"ms"},
#'   \code{"is"} or \code{"ibs"}. Default is \code{"poly"}.
#' @param winsor numeric vector of length 2, low and high percentiles for
#'   winsorizing \code{uvar}. Use \code{winsor_values = TRUE} to supply raw
#'   values instead of percentiles.
#' @param winsor_values logical; see \code{winsor}.
#' @param eqspace logical; if \code{TRUE}, knots are placed at equally spaced
#'   intervals instead of quantiles.
#' @param bknots numeric vector of length 2 with boundary knots for the spline
#'   basis. If \code{NULL} (default), boundary knots are set to the minimum and
#'   maximum of \code{uvar} (with a small padding). When supplied, the minimum
#'   and maximum of \code{uvar} must lie within \code{bknots}; otherwise an
#'   error is raised. Interior knot locations are still determined from
#'   \code{uvar}'s range or from \code{startp}/\code{endp}, not from
#'   \code{bknots}.
#' @param startp numeric; optional preset minimum internal knot. Together with
#'   \code{endp}, interior knots are placed between \code{startp} and
#'   \code{endp}; otherwise they follow the range of \code{uvar}.
#' @param endp numeric; optional preset maximum internal knot.
#' @param maxnk integer; maximum number of knots considered.
#' @param minnk integer; minimum number of knots considered.
#' @param center numeric; centering value for the spline basis.
#' @param absorb fixed-effects specification passed to \code{fixest::feols}.
#'   Can be a one-sided formula (e.g. \code{~ id + year}) or a character vector
#'   (e.g. \code{c("id", "year")}).
#' @param partialout \code{NULL} (no partial out), \code{"all"} (partial out
#'   all covariates, equivalent to Stata's \code{partialout}), or a character
#'   vector of variable names (equivalent to Stata's \code{partialout1(...)}).
#' @param cvgroup name of a variable that defines CV folds. If \code{NULL},
#'   folds are generated by clustering on \code{id}.
#' @param nfold number of CV folds when \code{cvgroup} is \code{NULL}.
#' @param seed integer random seed for fold generation.
#' @param degree polynomial degree for polynomial splines.
#' @param keepsplines logical; if \code{TRUE}, the generated spline columns are
#'   kept in the returned fitted object.
#' @param atu name of an alternative evaluation variable in \code{hf}. If
#'   supplied, the fitted semiparametric component is evaluated at \code{atu}
#'   instead of \code{uvar}.
#' @param dropfirstbase logical; if \code{TRUE}, the intercept/base term is
#'   dropped from the spline basis.
#' @param sopt logical; if \code{TRUE}, select the first local minimum of the CV
#'   curve instead of the global minimum.
#' @param bias_correct logical; if \code{TRUE} (default), compute a
#'   partitioning-based robust bias correction for the nonparametric component
#'   and report bias-corrected fitted values and standard errors.
#' @param bc_degree polynomial degree of the bias-correction spline basis. If
#'   \code{NULL} (default), it is set to \code{degree + 1}.
#' @param bc_type RBC method label. \code{"bc1"} returns the higher-order-basis
#'   prediction (\code{gen_bc1}) and \code{"bc2"} (the default) returns the
#'   least-squares bias-corrected prediction (\code{gen}). Both are computed
#'   and reported when \code{bias_correct = TRUE}.
#' @param predy name of a variable for the full predicted value (xb + fixed
#'   effects) at the low-frequency level. If \code{NULL}, none is computed.
#' @param weights name of a weight variable. Currently frequency, analytic and
#'   sampling weights are supported through \code{fixest}.
#'
#' @return A list with components \code{nknots}, \code{knots}, \code{cv_mse},
#'   \code{min_cv_mse}, \code{rmse}, \code{soptnk}, \code{coef},
#'   \code{coef_bc}, \code{vcov}, \code{vcov_bc}, \code{info},
#'   \code{fitted} (a data.table with \code{id}, \code{tl},
#'   \code{gen_raw}, \code{gen}, \code{gen_se} and, when
#'   \code{bias_correct = TRUE}, \code{gen_bc1}, \code{gen_bc1_se} and
#'   \code{gen_bc_se}), and the full \code{fixest} estimation object.
#'   \code{coef_bc} and \code{vcov_bc} are \code{NULL} when
#'   \code{bias_correct = FALSE}. \code{cv_mse} is a data.table of
#'   cross-validated RMSE by knot count (used to select \code{nknots});
#'   \code{min_cv_mse} is the minimum of that curve; \code{rmse} is the
#'   in-sample RMSE of the final \code{fixest::feols} fit.
#'
#' @details
#' The high-frequency data \code{hf} and the low-frequency data \code{lf} are
#' linked by the keys \code{id} and \code{tl}. The spline basis is generated on
#' \code{hf}, summed within each \code{id*tl} cell, and merged into \code{lf}
#' for estimation. This avoids storing the expanded spline basis at low
#' frequency and keeps memory use low.
#'
#' @export
mfxtsemipar_cv3 <- function(hf,
                           lf,
                           y,
                           x = NULL,
                           uvar,
                           id,
                           tl,
                           gen,
                           hfcov = NULL,
                           cluster = NULL,
                           type = "poly",
                           winsor = NULL,
                           winsor_values = FALSE,
                           eqspace = FALSE,
                           bknots = NULL,
                           startp = NULL,
                           endp = NULL,
                           maxnk = 5L,
                           minnk = 2L,
                           center = NULL,
                           absorb = NULL,
                           partialout = NULL,
                           cvgroup = NULL,
                           nfold = 10L,
                           seed = NULL,
                           degree = 1L,
                           keepsplines = FALSE,
                           atu = NULL,
                           dropfirstbase = FALSE,
                           sopt = FALSE,
                           bias_correct = TRUE,
                           bc_degree = NULL,
                           bc_type = c("bc2", "bc1"),
                           predy = NULL,
                           weights = NULL) {

  # ------------------------------------------------------------------
  # 0. package checks
  # ------------------------------------------------------------------
  if (!requireNamespace("data.table", quietly = TRUE)) {
    stop("Package 'data.table' is required.")
  }
  if (!requireNamespace("fixest", quietly = TRUE)) {
    stop("Package 'fixest' is required.")
  }
  if (!type %in% c("poly", "bs", "ms", "is", "ibs")) {
    stop("type must be one of 'poly', 'bs', 'ms', 'is', 'ibs'.")
  }
  if (type %in% c("ms", "is", "ibs") &&
      !requireNamespace("splines2", quietly = TRUE)) {
    stop("Package 'splines2' is required for type 'ms', 'is' and 'ibs'.")
  }

  bc_type <- match.arg(bc_type)
  if (!is.null(bc_degree) && (!is.numeric(bc_degree) || length(bc_degree) != 1L || bc_degree < 1L)) {
    stop("bc_degree must be a single positive integer.")
  }
  if (is.null(bc_degree)) {
    bc_degree <- as.integer(degree) + 1L
  } else {
    bc_degree <- as.integer(bc_degree)
  }
  if (bc_degree <= degree) {
    warning("bc_degree should be larger than degree for bias correction to be meaningful.")
  }

  # ------------------------------------------------------------------
  # 1. basic input validation and conversion
  # ------------------------------------------------------------------
  hf <- data.table::as.data.table(hf)
  lf <- data.table::as.data.table(lf)

  if (length(tl) == 1L && is.null(names(tl))) tl <- as.character(tl)
  keys <- c(id, tl)

  miss_hf <- setdiff(c(keys, uvar, hfcov, atu), names(hf))
  if (length(miss_hf)) {
    stop("Variables not found in hf: ", paste(miss_hf, collapse = ", "))
  }
  miss_lf <- setdiff(c(keys, y, x, cluster, cvgroup), names(lf))
  if (length(miss_lf)) {
    stop("Variables not found in lf: ", paste(miss_lf, collapse = ", "))
  }

  if (!is.null(weights)) {
    if (!(weights %in% names(hf)) && !(weights %in% names(lf))) {
      stop("Weights variable not found in hf or lf: ", weights)
    }
  }

  if (anyDuplicated(lf, by = keys)) {
    stop("lf must contain exactly one row per id*tl combination.")
  }

  if (!is.numeric(hf[[uvar]])) {
    stop("uvar must be numeric.")
  }

  weights_fml <- if (!is.null(weights)) stats::as.formula(paste0("~ ", weights)) else NULL

  # ------------------------------------------------------------------
  # 2. winsorize uvar if requested
  # ------------------------------------------------------------------
  if (!is.null(winsor)) {
    if (length(winsor) != 2L) {
      stop("winsor must be a numeric vector of length 2.")
    }
    if (winsor_values) {
      wlow <- winsor[1L]
      whigh <- winsor[2L]
    } else {
      quants <- stats::quantile(hf[[uvar]], probs = winsor / 100,
                                na.rm = TRUE, names = FALSE)
      wlow <- quants[1L]
      whigh <- quants[2L]
    }
    hf[, (uvar) := pmin(pmax(get(uvar), wlow), whigh)]
  }

  # ------------------------------------------------------------------
  # 3. determine knot boundaries
  # ------------------------------------------------------------------
  uvals <- hf[[uvar]]
  umin_data <- min(uvals, na.rm = TRUE)
  umax_data <- max(uvals, na.rm = TRUE)
  if (!is.finite(umin_data) || !is.finite(umax_data)) {
    stop("No non-missing observations available in uvar.")
  }

  if (is.null(bknots)) {
    bknots <- c(umin_data - 0.01, umax_data + 0.01)
  } else {
    bknots <- as.numeric(bknots)
    if (length(bknots) != 2L) {
      stop("bknots must be a numeric vector of length 2.")
    }
    if (bknots[1L] >= bknots[2L]) {
      stop("bknots must be strictly ascending.")
    }
    if (umin_data < bknots[1L]) {
      stop("Minimum uvar value (", umin_data,
           ") is below the lower boundary knot (", bknots[1L], ").",
           call. = FALSE)
    }
    if (umax_data > bknots[2L]) {
      stop("Maximum uvar value (", umax_data,
           ") is above the upper boundary knot (", bknots[2L], ").",
           call. = FALSE)
    }
  }

  if (!is.null(startp) && !is.numeric(startp)) {
    stop("startp must be numeric.")
  }
  if (!is.null(endp) && !is.numeric(endp)) {
    stop("endp must be numeric.")
  }
  if (!is.null(startp) && !is.null(endp) && startp >= endp) {
    stop("startp must be strictly less than endp.")
  }
  n_fixed_knots <- (!is.null(startp)) + (!is.null(endp))
  if (minnk < n_fixed_knots) {
    stop("minnk must be at least the number of specified startp/endp knots (",
         n_fixed_knots, ").", call. = FALSE)
  }

  # ------------------------------------------------------------------
  # 4. generate CV groups
  # ------------------------------------------------------------------
  if (!is.null(cvgroup)) {
    lf[, .cv := as.integer(as.factor(get(cvgroup)))]
  } else {
    if (!is.null(seed)) set.seed(seed)
    ids <- unique(lf[[id]])
    folds <- sample(rep_len(seq_len(nfold), length(ids)))
    map <- data.table::data.table(.id = ids, .cv = folds)
    data.table::setnames(map, ".id", id)
    lf <- merge(lf, map, by = id, all.x = TRUE)
  }

  # ------------------------------------------------------------------
  # 5. split controls into main / partialout
  # ------------------------------------------------------------------
  all_controls <- unique(c(x, hfcov))
  if (is.null(partialout)) {
    x_main <- all_controls
    x_partial <- NULL
  } else if (identical(partialout, "all")) {
    x_main <- NULL
    x_partial <- all_controls
  } else {
    partialout <- as.character(partialout)
    x_partial <- intersect(partialout, all_controls)
    if (length(setdiff(partialout, all_controls))) {
      warning("Some partialout variables are not in x or hfcov: ",
              paste(setdiff(partialout, all_controls), collapse = ", "))
    }
    x_main <- setdiff(all_controls, x_partial)
  }

  # ------------------------------------------------------------------
  # 6. cross-validation over nknots
  # ------------------------------------------------------------------
  cv_rmse_vec <- rep(NA_real_, maxnk - minnk + 1L)
  names(cv_rmse_vec) <- paste0("nk=", seq(minnk, maxnk))

  for (i in seq_along(cv_rmse_vec)) {
    nk <- minnk + i - 1L

    knots <- gennknots(hf[[uvar]], nknots = nk, eqspace = eqspace,
                       startp = startp, endp = endp)

    sp <- make_splines(
      x = hf[[uvar]],
      type = type,
      knots = knots,
      bknots = bknots,
      degree = degree,
      center = center,
      intercept = !dropfirstbase,
      prefix = ".Spline_"
    )
    spline_vars <- sp$names
    add_splines_to_hf(hf, sp$matrix, spline_vars)

    lf_agg <- agg_hf_to_lf(
      hf = hf,
      id = id,
      tl = tl,
      spline_vars = spline_vars,
      hfcov = hfcov,
      weights = weights
    )

    # remove temporary spline columns from hf to save memory
    hf[, (spline_vars) := NULL]

    lf_cv <- merge(lf, lf_agg, by = keys, all.x = TRUE)

    cv_rmse_vec[i] <- rmse_cv(
      data = lf_cv,
      y = y,
      varlist = c(spline_vars, x_main),
      partialout = x_partial,
      absorb = absorb,
      cluster = cluster,
      weights_fml = weights_fml,
      cvvar = ".cv"
    )
  }

  # select optimal knots
  minpos <- which.min(cv_rmse_vec)
  soptnk <- minnk + minpos - 1L

  if (sopt) {
    soptnk <- minnk
    for (k in seq(minnk, maxnk)) {
      idx <- k - minnk + 1L
      if (!is.na(cv_rmse_vec[idx]) &&
          (idx == 1L || cv_rmse_vec[idx] < cv_rmse_vec[idx - 1L])) {
        soptnk <- k
      } else {
        break
      }
    }
  }

  nknots <- if (sopt) soptnk else (minnk + minpos - 1L)
  min_cv_mse <- cv_rmse_vec[minpos]

  cat("\nCross-validation RMSE (for knot selection)\n")
  print(data.table::data.table(nk = seq(minnk, maxnk), cv_rmse = cv_rmse_vec))
  cat("\n")

  # ------------------------------------------------------------------
  # 7. final estimation with optimal knots
  # ------------------------------------------------------------------
  knots <- gennknots(hf[[uvar]], nknots = nknots, eqspace = eqspace,
                     startp = startp, endp = endp)

  sp <- make_splines(
    x = hf[[uvar]],
    type = type,
    knots = knots,
    bknots = bknots,
    degree = degree,
    center = center,
    intercept = !dropfirstbase,
    prefix = ".Spline_"
  )
  spline_vars <- sp$names
  spline_cmd <- sp$call
  add_splines_to_hf(hf, sp$matrix, spline_vars)

  lf_agg <- agg_hf_to_lf(
    hf = hf,
    id = id,
    tl = tl,
    spline_vars = spline_vars,
    hfcov = hfcov,
    weights = weights
  )

  hf[, (spline_vars) := NULL]

  lf_est <- merge(lf, lf_agg, by = keys, all.x = TRUE)

  cluster_fml <- if (!is.null(cluster)) stats::as.formula(paste0("~ ", cluster)) else NULL

  # ------------------------------------------------------------------
  # 8. main regression (raw point estimate and raw SE)
  # ------------------------------------------------------------------
  fml_main <- build_formula(y = y, varlist = c(spline_vars, x_main),
                            partialout = x_partial, absorb = absorb)
  est_main <- fixest::feols(fml_main, data = lf_est, cluster = cluster_fml,
                            weights = weights_fml, warn = FALSE, notes = FALSE)
  b_main <- stats::coef(est_main)
  V_main <- stats::vcov(est_main)
  retained_spline_main <- intersect(names(b_main), spline_vars)

  # ------------------------------------------------------------------
  # 9. robust bias correction basis and stacked regression
  # ------------------------------------------------------------------
  bc_spline_vars <- NULL
  bc_spline_cmd <- NULL
  sp_bc <- NULL
  bc_G0 <- NULL
  bc_M <- NULL
  est_stack <- NULL
  if (bias_correct) {
    sp_bc <- make_splines(
      x = hf[[uvar]],
      type = type,
      knots = knots,
      bknots = bknots,
      degree = bc_degree,
      center = center,
      intercept = !dropfirstbase,
      prefix = ".SplineBC_"
    )
    bc_spline_vars <- sp_bc$names
    bc_spline_cmd <- sp_bc$call
    add_splines_to_hf(hf, sp_bc$matrix, bc_spline_vars)

    lf_agg_bc <- agg_hf_to_lf(
      hf = hf,
      id = id,
      tl = tl,
      spline_vars = bc_spline_vars,
      hfcov = NULL,
      weights = weights
    )

    hf[, (bc_spline_vars) := NULL]

    lf_est <- merge(lf_est, lf_agg_bc, by = keys, all.x = TRUE)

    # Build stacked regression data: two equations, main (eq=0) and BC (eq=1).
    # Each equation retains its own coefficients for B, \tilde{B}, x and partialout
    # variables, and FE are interacted with the equation indicator. Clustering by
    # the original cluster variable preserves the cross-equation covariance.
    lf_stack <- data.table::rbindlist(list(lf_est, lf_est))
    lf_stack[, .eq := rep(c(0L, 1L), each = nrow(lf_est))]

    eq0_vars <- character()
    eq1_vars <- character()

    make_eq_col <- function(var, eq) {
      ifelse(lf_stack$.eq == eq, lf_stack[[var]], 0)
    }

    for (var in spline_vars) {
      v0 <- paste0(var, "_eq0")
      lf_stack[, (v0) := make_eq_col(var, 0L)]
      eq0_vars <- c(eq0_vars, v0)
    }

    for (var in bc_spline_vars) {
      v1 <- paste0(var, "_eq1")
      lf_stack[, (v1) := make_eq_col(var, 1L)]
      eq1_vars <- c(eq1_vars, v1)
    }

    all_controls <- unique(c(x_main, x_partial))
    for (var in all_controls) {
      v0 <- paste0(var, "_eq0")
      v1 <- paste0(var, "_eq1")
      lf_stack[, (v0) := make_eq_col(var, 0L)]
      lf_stack[, (v1) := make_eq_col(var, 1L)]
      eq0_vars <- c(eq0_vars, v0)
      eq1_vars <- c(eq1_vars, v1)
    }

    # Stacked regression: main equation (eq=0) uses the original spline basis
    # and controls; BC equation (eq=1) uses the higher-order BC basis and the
    # same controls. Fixed effects are interacted with the equation indicator.
    active_vars <- c(eq0_vars, eq1_vars)

    # Build stacked formula: y ~ active_vars | FE^.eq
    rhs <- paste(active_vars, collapse = " + ")
    fml_stack <- paste0(y, " ~ ", rhs)

    if (!is.null(absorb)) {
      if (inherits(absorb, "formula")) {
        abs_txt <- paste(deparse(absorb), collapse = "")
        abs_txt <- sub("^\\s*~\\s*", "", abs_txt)
      } else {
        abs_txt <- paste(absorb, collapse = " + ")
      }
      fml_stack <- paste0(fml_stack, " | ", abs_txt, "^.eq")
    } else {
      fml_stack <- paste0(fml_stack, " | .eq")
    }
    fml_stack <- stats::as.formula(fml_stack)

    est_stack <- fixest::feols(fml_stack, data = lf_stack, cluster = cluster_fml,
                               weights = weights_fml, warn = FALSE, notes = FALSE)

    # Coefficients for main equation: those ending in _eq0 and retained by fixest
    b_stack <- stats::coef(est_stack)
    nm0 <- names(b_stack)
    main_coef_names <- paste0(retained_spline_main, "_eq0")
    bc_coef_names <- paste0(bc_spline_vars, "_eq1")
    retained_spline_stack <- intersect(nm0, main_coef_names)
    retained_bc_stack <- intersect(nm0, bc_coef_names)

    # Map back to original names
    retained_spline <- sub("_eq0$", "", retained_spline_stack)
    retained_bc <- sub("_eq1$", "", retained_bc_stack)
    names(b_stack)[nm0 %in% retained_spline_stack] <- retained_spline
    names(b_stack)[nm0 %in% retained_bc_stack] <- retained_bc

    b_main <- b_stack[retained_spline]
    V_stack <- stats::vcov(est_stack)
    V_main <- V_stack[retained_spline_stack, retained_spline_stack, drop = FALSE]
    rownames(V_main) <- colnames(V_main) <- retained_spline

    all_retained <- c(retained_spline, retained_bc)
    all_retained_stack <- c(retained_spline_stack, retained_bc_stack)
    b_bc <- b_stack[all_retained]
    V_bc <- V_stack[all_retained_stack, all_retained_stack, drop = FALSE]
    rownames(V_bc) <- colnames(V_bc) <- all_retained

    # Cross-moments for bc2 projection matrix (use non-stacked lf_est)
    B_lf <- as.matrix(lf_est[, retained_spline, with = FALSE])
    Btilde_lf <- as.matrix(lf_est[, retained_bc, with = FALSE])
    wvec <- if (!is.null(weights)) lf_est[[weights]] else rep(1, nrow(lf_est))
    cc <- complete.cases(B_lf, Btilde_lf, wvec)
    B_lf <- B_lf[cc, , drop = FALSE]
    Btilde_lf <- Btilde_lf[cc, , drop = FALSE]
    wvec <- wvec[cc]
    sw <- sqrt(wvec)
    B_lf_w <- B_lf * sw
    Btilde_lf_w <- Btilde_lf * sw
    bc_G0 <- solve(crossprod(B_lf_w) / sum(wvec))
    bc_M <- crossprod(B_lf_w, Btilde_lf_w) / sum(wvec)
    colnames(bc_M) <- retained_bc
  }

  est <- if (bias_correct) est_stack else est_main
  b <- b_main
  V <- V_main
  b_bc <- if (bias_correct) b_bc else NULL
  V_bc <- if (bias_correct) V_bc else NULL

  info <- fixest::fitstat(est, type = c("ll", "aic", "bic", "n"))
  rmse <- sqrt(mean(stats::residuals(est_main)^2, na.rm = TRUE))

  # ------------------------------------------------------------------
  # 9. prediction: semiparametric component
  # ------------------------------------------------------------------
  eval_var <- if (!is.null(atu)) atu else uvar
  eval_x <- hf[[eval_var]]

  sp_eval <- make_splines(
    x = eval_x,
    type = type,
    knots = knots,
    bknots = bknots,
    degree = degree,
    center = center,
    intercept = !dropfirstbase,
    prefix = ".Spline_"
  )
  B_eval <- sp_eval$matrix

  retained_spline <- intersect(names(b), spline_vars)
  if (length(retained_spline) == 0L) {
    stop("All spline coefficients were dropped; check collinearity.")
  }
  B_eval_retained <- B_eval[, retained_spline, drop = FALSE]

  # raw estimate and SE
  b_spline <- b[retained_spline]
  fitted_vals_raw <- as.numeric(B_eval_retained %*% b_spline)
  V_raw <- V[retained_spline, retained_spline, drop = FALSE]
  se_vals_raw <- sqrt(pmax(0, rowSums((B_eval_retained %*% V_raw) * B_eval_retained)))

  fitted_vals_bc <- fitted_vals_raw
  se_vals_bc <- se_vals_raw

  if (bias_correct) {
    sp_bc_eval <- make_splines(
      x = eval_x,
      type = type,
      knots = knots,
      bknots = bknots,
      degree = bc_degree,
      center = center,
      intercept = !dropfirstbase,
      prefix = ".SplineBC_"
    )
    Btilde_eval <- sp_bc_eval$matrix

    retained_bc <- intersect(names(b_bc), bc_spline_vars)
    if (length(retained_bc) == 0L) {
      stop("All bias-correction spline coefficients were dropped; check collinearity.")
    }
    Btilde_eval_retained <- Btilde_eval[, retained_bc, drop = FALSE]

    all_retained <- c(retained_spline, retained_bc)
    b_joint <- b_bc[all_retained]
    V_joint <- V_bc[all_retained, all_retained, drop = FALSE]

    # bc1: direct higher-order-basis prediction.
    fitted_vals_bc1 <- as.numeric(Btilde_eval_retained %*% b_joint[retained_bc])
    se_vals_bc1 <- sqrt(pmax(0, rowSums((Btilde_eval_retained %*%
                                          V_joint[retained_bc, retained_bc, drop = FALSE]) * Btilde_eval_retained)))

    # bc2: main basis prediction + orthogonalized BC correction.
    # Projection bc_M was computed for all BC basis columns; subset to retained.
    proj_main <- bc_G0 %*% bc_M[, retained_bc, drop = FALSE]
    w_bc2 <- cbind(B_eval_retained, Btilde_eval_retained - B_eval_retained %*% proj_main)

    fitted_vals_bc2 <- as.numeric(w_bc2 %*% b_joint)
    se_vals_bc2 <- sqrt(pmax(0, rowSums((w_bc2 %*% V_joint) * w_bc2)))

    if (bc_type == "bc1") {
      fitted_vals_bc <- fitted_vals_bc1
      se_vals_bc <- se_vals_bc1
    } else {
      fitted_vals_bc <- fitted_vals_bc2
      se_vals_bc <- se_vals_bc2
    }
  }

  out_dt <- data.table::copy(hf[, c(keys, if (!is.null(atu)) atu else uvar), with = FALSE])
  out_dt[, (paste0(gen, "_raw")) := fitted_vals_raw]
  out_dt[, (gen) := fitted_vals_bc]
  out_dt[, (paste0(gen, "_se")) := se_vals_raw]
  if (bias_correct) {
    out_dt[, (paste0(gen, "_bc1")) := fitted_vals_bc1]
    out_dt[, (paste0(gen, "_bc1_se")) := se_vals_bc1]
    out_dt[, (paste0(gen, "_bc_se")) := se_vals_bc]
  }

  if (keepsplines) {
    for (j in seq_along(spline_vars)) {
      out_dt[, (spline_vars[j]) := B_eval[, j]]
    }
  }

  # ------------------------------------------------------------------
  # 10. predy: full prediction at low frequency
  # ------------------------------------------------------------------
  predy_dt <- NULL
  if (!is.null(predy)) {
    # Use the non-stacked main regression for the low-frequency full prediction.
    lf_est[, (predy) := stats::predict(est_main, type = "response")]
    predy_dt <- lf_est[, c(keys, predy), with = FALSE]
    out_dt <- merge(out_dt, predy_dt, by = keys, all.x = TRUE)
  }

  # ------------------------------------------------------------------
  # 11. return
  # ------------------------------------------------------------------
  result <- list(
    soptnk = soptnk,
    nknots = nknots,
    knots = knots,
    bknots = bknots,
    min_cv_mse = min_cv_mse,
    cv_mse = data.table::data.table(nk = seq(minnk, maxnk), cv_rmse = cv_rmse_vec),
    rmse = rmse,
    splinecmd = spline_cmd,
    type = type,
    degree = degree,
    center = if (is.null(center)) 0 else center,
    intercept = !dropfirstbase,
    uvar = uvar,
    startp = startp,
    endp = endp,
    id = id,
    tl = tl,
    coef = b,
    coef_bc = if (bias_correct) b_bc else NULL,
    vcov = V,
    vcov_bc = if (bias_correct) V_bc else NULL,
    info = info,
    fitted = out_dt,
    predy = predy_dt,
    estimation = est,
    bc_type = if (bias_correct) bc_type else NULL,
    bc_degree = if (bias_correct) bc_degree else NULL,
    bc_splinecmd = bc_spline_cmd,
    bc_G0 = if (bias_correct) bc_G0 else NULL,
    bc_M = if (bias_correct) bc_M else NULL,
    bc_retained_spline = if (bias_correct) retained_spline else NULL,
    bc_retained_bc = if (bias_correct) retained_bc else NULL,
    call = match.call()
  )

  class(result) <- c("mfxtsemipar_cv3", "list")
  return(result)
}


# ==============================================================================
# Helper: generate knots
# ==============================================================================
gennknots <- function(x, nknots, eqspace = FALSE,
                      startp = NULL, endp = NULL) {
  x <- x[!is.na(x)]
  if (length(x) == 0L) {
    stop("No non-missing observations available to form knots.")
  }

  n_fixed <- (!is.null(startp)) + (!is.null(endp))
  n_middle <- as.integer(nknots - n_fixed)
  if (n_middle < 0L) {
    stop("nknots must be at least the number of specified startp/endp knots.")
  }

  lo <- if (!is.null(startp)) startp else min(x)
  hi <- if (!is.null(endp)) endp else max(x)
  if (!is.finite(lo) || !is.finite(hi) || lo >= hi) {
    stop("Invalid knot range: startp must be strictly less than endp.")
  }

  if (n_middle == 0L) {
    cuts <- c(
      if (!is.null(startp)) startp,
      if (!is.null(endp)) endp
    )
    return(cuts)
  }

  if (eqspace) {
    step <- (hi - lo) / (n_middle + 1L)
    middle <- seq(lo + step, hi - step, length.out = n_middle)
  } else {
    if (!is.null(startp) && !is.null(endp)) {
      keep <- x >= startp & x < endp
    } else if (!is.null(endp)) {
      keep <- x < endp
    } else if (!is.null(startp)) {
      keep <- x >= startp
    } else {
      keep <- rep(TRUE, length(x))
    }

    if (sum(keep) < n_middle + 1L) {
      stop("Not enough observations inside [startp, endp] to form knots.")
    }
    probs <- seq_len(n_middle) / (n_middle + 1L)
    middle <- as.numeric(stats::quantile(x[keep], probs = probs,
                                         type = 2, names = FALSE))
  }

  cuts <- c(
    if (!is.null(startp)) startp,
    middle,
    if (!is.null(endp)) endp
  )
  return(cuts)
}


# ==============================================================================
# Helper: build spline basis
# ==============================================================================
make_splines <- function(x, type, knots, bknots, degree = 1L,
                         center = NULL, intercept = TRUE,
                         prefix = ".Spline_") {
  if (is.null(center)) center <- 0

  out <- switch(type,
    poly = polysplines(x, knots, degree, center, intercept, prefix),
    bs   = bs_splines(x, knots, bknots, degree, center, intercept, prefix),
    ms   = ms_splines(x, knots, bknots, degree, intercept, prefix),
    is   = is_splines(x, knots, bknots, degree, intercept, prefix),
    ibs  = ibs_splines(x, knots, bknots, degree, intercept, prefix)
  )

  out$call <- paste0(
    type, " splines: degree=", degree,
    ", knots=c(", paste(round(knots, 4), collapse = ", "),
    "), bknots=c(", paste(round(bknots, 4), collapse = ", "), ")"
  )
  return(out)
}


polysplines <- function(x, knots, degree = 1L, center = 0,
                        intercept = TRUE, prefix = ".Spline_") {
  n <- length(x)
  p <- as.integer(degree)
  j <- 1L
  vars <- character()
  mat <- matrix(0, nrow = n, ncol = 0L)

  for (pow in seq_len(p)) {
    v <- paste0(prefix, j)
    vars <- c(vars, v)
    mat <- cbind(mat, x^pow - center^pow)
    j <- j + 1L
  }

  for (k in knots) {
    v <- paste0(prefix, j)
    vars <- c(vars, v)
    mat <- cbind(mat,
      (x - k)^p * (x > k) - (center - k)^p * (center > k)
    )
    j <- j + 1L
  }

  if (intercept) {
    v0 <- paste0(prefix, "0")
    vars <- c(v0, vars)
    mat <- cbind(1, mat)
  }

  colnames(mat) <- vars
  list(matrix = mat, names = vars)
}


bs_splines <- function(x, knots, bknots, degree = 3L, center = 0,
                       intercept = TRUE, prefix = ".Spline_") {
  # Use splines2::bSpline to match Stata gensplines type(bs)
  B <- splines2::bSpline(x, knots = knots, Boundary.knots = bknots,
                         degree = degree, intercept = intercept)
  B <- as.matrix(B)

  # Apply centering (centerv): B(x) - B(center)
  B_center <- splines2::bSpline(center, knots = knots, Boundary.knots = bknots,
                               degree = degree, intercept = intercept)
  B <- sweep(B, 2, as.numeric(B_center), "-")

  start_idx <- ifelse(intercept, 0L, 1L)
  vars <- paste0(prefix, start_idx:(start_idx + ncol(B) - 1L))
  colnames(B) <- vars
  list(matrix = B, names = vars)
}


ms_splines <- function(x, knots, bknots, degree = 3L,
                       intercept = TRUE, prefix = ".Spline_") {
  B <- splines2::mSpline(x, knots = knots, Boundary.knots = bknots,
                         degree = degree, intercept = intercept)
  vars <- paste0(prefix, seq_len(ncol(B)) - ifelse(intercept, 1L, 0L))
  colnames(B) <- vars
  list(matrix = as.matrix(B), names = vars)
}


is_splines <- function(x, knots, bknots, degree = 2L,
                       intercept = TRUE, prefix = ".Spline_") {
  B <- splines2::iSpline(x, knots = knots, Boundary.knots = bknots,
                         degree = degree, intercept = intercept)
  vars <- paste0(prefix, seq_len(ncol(B)) - ifelse(intercept, 1L, 0L))
  colnames(B) <- vars
  list(matrix = as.matrix(B), names = vars)
}


ibs_splines <- function(x, knots, bknots, degree = 3L,
                        intercept = TRUE, prefix = ".Spline_") {
  B <- splines2::ibs(x, knots = knots, Boundary.knots = bknots,
                     degree = degree, intercept = intercept)
  vars <- paste0(prefix, seq_len(ncol(B)) - ifelse(intercept, 1L, 0L))
  colnames(B) <- vars
  list(matrix = as.matrix(B), names = vars)
}


# ==============================================================================
# Helper: attach spline matrix to hf without copying
# ==============================================================================
add_splines_to_hf <- function(hf, mat, names) {
  for (j in seq_along(names)) {
    data.table::set(hf, j = names[j], value = mat[, j])
  }
}


# ==============================================================================
# Helper: aggregate high-frequency spline basis to low frequency
# ==============================================================================
agg_hf_to_lf <- function(hf, id, tl, spline_vars,
                         hfcov = NULL, weights = NULL) {
  keys <- c(id, tl)

  agg <- hf[, lapply(.SD, sum, na.rm = TRUE), by = keys, .SDcols = spline_vars]

  if (length(hfcov)) {
    means <- hf[, lapply(.SD, mean, na.rm = TRUE), by = keys, .SDcols = hfcov]
    agg <- merge(agg, means, by = keys, all.x = TRUE)
  }

  if (!is.null(weights) && weights %in% names(hf)) {
    wmean <- hf[, lapply(.SD, mean, na.rm = TRUE), by = keys, .SDcols = weights]
    agg <- merge(agg, wmean, by = keys, all.x = TRUE)
  }

  return(agg)
}


# ==============================================================================
# Helper: build fixest formula (no weights here)
# ==============================================================================
build_formula <- function(y, varlist, partialout = NULL, absorb = NULL) {
  rhs <- paste(c(varlist, partialout), collapse = " + ")
  if (nzchar(rhs)) {
    fml <- paste0(y, " ~ ", rhs)
  } else {
    fml <- paste0(y, " ~ 0")
  }

  if (!is.null(absorb)) {
    if (inherits(absorb, "formula")) {
      abs_txt <- paste(deparse(absorb), collapse = "")
      abs_txt <- sub("^\\s*~\\s*", "", abs_txt)
    } else {
      abs_txt <- paste(absorb, collapse = " + ")
    }
    fml <- paste0(fml, " | ", abs_txt)
  }

  stats::as.formula(fml)
}


# ==============================================================================
# Helper: residualization formula (matches reghdfe y depvar [partialout] [, absorb])
# ==============================================================================
fml_residualize <- function(y, x_partial = NULL, absorb = NULL) {
  if (length(x_partial) > 0L || !is.null(absorb)) {
    build_formula(y = y, varlist = x_partial, partialout = NULL, absorb = absorb)
  } else {
    stats::as.formula(paste0(y, " ~ 1"))
  }
}


# ==============================================================================
# Helper: save outf data to file
# ==============================================================================
outf_save <- function(dt, save, replace = FALSE) {
  if (!replace && file.exists(save)) {
    stop("File '", save, "' already exists. Use replace = TRUE to overwrite.")
  }
  ext <- tolower(tools::file_ext(save))
  if (ext == "csv") {
    data.table::fwrite(dt, save)
  } else if (ext %in% c("rdata", "rda")) {
    outf_data <- dt
    save(outf_data, file = save)
  } else {
    saveRDS(dt, save)
  }
}


# ==============================================================================
# Helper: cross-validation RMSE
# ==============================================================================
rmse_cv <- function(data, y, varlist, partialout = NULL,
                    absorb = NULL, cluster = NULL, weights_fml = NULL,
                    cvvar = ".cv") {
  data <- data.table::as.data.table(data)
  folds <- sort(unique(data[[cvvar]]))

  resi2 <- numeric(nrow(data))
  nvars <- length(varlist)

  fml <- build_formula(y = y, varlist = varlist,
                       partialout = partialout, absorb = absorb)
  cluster_fml <- if (!is.null(cluster)) stats::as.formula(paste0("~ ", cluster)) else NULL

  for (f in folds) {
    train <- data[get(cvvar) != f]
    val   <- data[get(cvvar) == f]

    fit <- fixest::feols(fml, data = train, cluster = cluster_fml,
                         weights = weights_fml, warn = FALSE, notes = FALSE)

    b <- stats::coef(fit)
    # allow for collinear drops: keep only coefficients that correspond to varlist
    retained <- intersect(names(b), varlist)
    if (length(retained) == 0L) {
      stop("All varlist variables were dropped; check collinearity.")
    }
    b <- b[retained]

    X_val <- as.matrix(val[, retained, with = FALSE])
    y_val <- val[[y]]
    gjhat <- as.numeric(X_val %*% b)
    resid <- y_val - gjhat

    val_fit <- NULL
    if (length(partialout)) {
      val_dt <- data.table::as.data.table(val)
      val_dt[, .resid := resid]
      val_fml <- build_formula(y = ".resid", varlist = partialout,
                               partialout = NULL, absorb = absorb)
      val_fit <- tryCatch(
        fixest::feols(val_fml, data = val_dt, cluster = cluster_fml,
                      weights = weights_fml, warn = FALSE, notes = FALSE),
        error = function(e) NULL
      )
    }

    if (is.null(val_fit) && !is.null(absorb)) {
      # fall back to fixed-effects only (all partialout vars collinear with FE)
      val_dt <- data.table::as.data.table(val)
      val_dt[, .resid := resid]
      val_fml <- build_formula(y = ".resid", varlist = NULL,
                               partialout = NULL, absorb = absorb)
      val_fit <- fixest::feols(val_fml, data = val_dt, cluster = cluster_fml,
                               weights = weights_fml, warn = FALSE, notes = FALSE)
    }

    if (!is.null(val_fit)) {
      yhat_val <- stats::predict(val_fit, type = "response")
      err <- resid - yhat_val
    } else {
      err <- resid
    }

    resi2[data[[cvvar]] == f] <- err^2
  }

  return(sqrt(mean(resi2, na.rm = TRUE)))
}


# ==============================================================================
# Print method
# ==============================================================================
#' @export
print.mfxtsemipar_cv3 <- function(x, ...) {
  cat("Mixed-frequency semiparametric regression with cross-validation and robust bias correction\n")
  cat("  Selected knots: ", x$nknots, "\n", sep = "")
  cat("  Boundary knots: ", paste(round(x$bknots, 4), collapse = ", "), "\n", sep = "")
  cat("  Knot locations: ", paste(round(x$knots, 4), collapse = ", "), "\n", sep = "")
  cat("  Minimum CV RMSE: ", round(x$min_cv_mse, 6), "\n", sep = "")
  cat("  Final fit RMSE: ", round(x$rmse, 6), "\n", sep = "")
  cat("  Simple optimal knots: ", x$soptnk, "\n", sep = "")
  bc_type <- if (!is.null(x$bc_type)) paste0(x$bc_type, " (degree ", x$bc_degree, ")") else "none"
  cat("  Bias correction: ", bc_type, "\n", sep = "")
  cat("\nCV RMSE by number of knots:\n")
  print(x$cv_mse, row.names = FALSE)
  invisible(x)
}


# ==============================================================================
# Predict method for g(u)
# ==============================================================================
#' Predict the semiparametric component g(u) from an mfxtsemipar_cv3 fit
#'
#' Given a new set of values for the semiparametric variable \code{uvar},
#' reconstructs the spline basis using the estimated knots and settings, then
#' returns the fitted semiparametric component and its delta-method standard
#' error.
#'
#' @param object an object of class \code{mfxtsemipar_cv3}.
#' @param newdata a data.frame or data.table containing the evaluation variable,
#'   or a numeric vector of evaluation points.
#' @param uvar name of the evaluation variable in \code{newdata}. If
#'   \code{NULL}, the \code{uvar} used in estimation is used.
#' @param bias_correct logical; if \code{TRUE} (default), use the bias-corrected
#'   estimate when available; otherwise use the raw estimate.
#' @param ... additional arguments (currently ignored).
#'
#' @return A data.table with columns \code{u}, \code{g} (the predicted
#'   g(u)), and \code{se}.
#'
#' @export
predict.mfxtsemipar_cv3 <- function(object, newdata, uvar = NULL,
                                    bias_correct = TRUE, ...) {
  if (!inherits(object, "mfxtsemipar_cv3")) {
    stop("object must be of class 'mfxtsemipar_cv3'.")
  }

  if (is.numeric(newdata)) {
    x <- newdata
    if (is.null(uvar)) uvar <- object$uvar
  } else {
    newdata <- data.table::as.data.table(newdata)
    if (is.null(uvar)) uvar <- object$uvar
    if (!(uvar %in% names(newdata))) {
      stop("Variable '", uvar, "' not found in newdata.")
    }
    x <- newdata[[uvar]]
  }

  if (!is.numeric(x)) {
    stop("Evaluation variable must be numeric.")
  }

  sp <- make_splines(
    x = x,
    type = object$type,
    knots = object$knots,
    bknots = object$bknots,
    degree = object$degree,
    center = object$center,
    intercept = object$intercept,
    prefix = ".Spline_"
  )
  B <- sp$matrix
  spline_vars <- sp$names

  retained <- intersect(names(object$coef), spline_vars)
  if (length(retained) == 0L) {
    stop("No spline coefficients available for prediction.")
  }

  B_retained <- B[, retained, drop = FALSE]

  if (bias_correct && !is.null(object$bc_type)) {
    bc_type <- object$bc_type
    retained_bc <- object$bc_retained_bc

    sp_bc <- make_splines(
      x = x,
      type = object$type,
      knots = object$knots,
      bknots = object$bknots,
      degree = object$bc_degree,
      center = object$center,
      intercept = object$intercept,
      prefix = ".SplineBC_"
    )
    Btilde <- sp_bc$matrix
    Btilde_retained <- Btilde[, retained_bc, drop = FALSE]

    all_retained <- c(retained, retained_bc)
    b_joint <- object$coef_bc[all_retained]
    V_joint <- object$vcov_bc[all_retained, all_retained, drop = FALSE]

    # Orthogonalize BC evaluation basis using the stored projection.
    # bc_M was computed for all BC basis columns; subset to those retained
    # in the joint regression.
    proj_main <- object$bc_G0 %*% object$bc_M[, retained_bc, drop = FALSE]
    Btilde_orth_retained <- Btilde_retained - B_retained %*% proj_main

    w_bc <- cbind(B_retained, Btilde_orth_retained)

    fit <- as.numeric(w_bc %*% b_joint)
    se <- sqrt(pmax(0, rowSums((w_bc %*% V_joint) * w_bc)))
  } else {
    b <- object$coef[retained]
    fit <- as.numeric(B_retained %*% b)
    V <- object$vcov[retained, retained, drop = FALSE]
    se <- sqrt(pmax(0, rowSums((B_retained %*% V) * B_retained)))
  }

  out <- data.table::data.table(u = x, g = fit, se = se)
  out
}


# ==============================================================================
# Diagnostic: compare estimated g(u) to true g(u)
# ==============================================================================
#' Compare the estimated semiparametric component to a true g(u)
#'
#' Predicts g(u) at the evaluation points provided in \code{newdata} and reports
#' standard accuracy metrics against the supplied true values.
#'
#' @param object an object of class \code{mfxtsemipar_cv3}.
#' @param newdata a data.frame or data.table containing the evaluation variable,
#'   or a numeric vector of evaluation points.
#' @param true_g numeric vector of true g(u) values, aligned with \code{newdata}.
#' @param uvar name of the evaluation variable in \code{newdata}. If
#'   \code{NULL}, the \code{uvar} used in estimation is used.
#' @param bias_correct logical; passed to \code{predict.mfxtsemipar_cv3}.
#'
#' @return A list with components \code{metrics} (a one-row data.table),
#'   \code{pred} (the prediction data.table), and \code{resid} (true - fitted).
#'
#' @export
g_diagnostic <- function(object, ...) {
  UseMethod("g_diagnostic")
}

g_diagnostic.mfxtsemipar_cv3 <- function(object, newdata, true_g,
                                         uvar = NULL, bias_correct = TRUE) {
  pred <- predict.mfxtsemipar_cv3(object, newdata = newdata, uvar = uvar,
                                  bias_correct = bias_correct)
  compute_g_diagnostic(pred, true_g)
}

compute_g_diagnostic <- function(pred, true_g) {
  fit <- pred$g
  se <- pred$se

  if (length(true_g) != length(fit)) {
    stop("length(true_g) must equal the number of evaluation points.")
  }

  resid <- true_g - fit

  metrics <- data.table::data.table(
    n = length(fit),
    mse = mean(resid^2, na.rm = TRUE),
    rmse = sqrt(mean(resid^2, na.rm = TRUE)),
    mae = mean(abs(resid), na.rm = TRUE),
    corr = stats::cor(fit, true_g, use = "pairwise.complete.obs"),
    max_abs_err = max(abs(resid), na.rm = TRUE),
    mean_se = mean(se, na.rm = TRUE)
  )

  list(metrics = metrics, pred = pred, resid = resid)
}
